// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Types (11)
//--------------------------------------------------------------------------------
typedef enum {
    DEVPROP_OPERATOR_MODIFIER_NOT = 65536,
    DEVPROP_OPERATOR_MODIFIER_IGNORE_CASE = 131072,
    DEVPROP_OPERATOR_NONE = 0,
    DEVPROP_OPERATOR_EXISTS = 1,
    DEVPROP_OPERATOR_NOT_EXISTS = 65537,
    DEVPROP_OPERATOR_EQUALS = 2,
    DEVPROP_OPERATOR_NOT_EQUALS = 65538,
    DEVPROP_OPERATOR_GREATER_THAN = 3,
    DEVPROP_OPERATOR_LESS_THAN = 4,
    DEVPROP_OPERATOR_GREATER_THAN_EQUALS = 5,
    DEVPROP_OPERATOR_LESS_THAN_EQUALS = 6,
    DEVPROP_OPERATOR_EQUALS_IGNORE_CASE = 131074,
    DEVPROP_OPERATOR_NOT_EQUALS_IGNORE_CASE = 196610,
    DEVPROP_OPERATOR_BITWISE_AND = 7,
    DEVPROP_OPERATOR_BITWISE_OR = 8,
    DEVPROP_OPERATOR_BEGINS_WITH = 9,
    DEVPROP_OPERATOR_ENDS_WITH = 10,
    DEVPROP_OPERATOR_CONTAINS = 11,
    DEVPROP_OPERATOR_BEGINS_WITH_IGNORE_CASE = 131081,
    DEVPROP_OPERATOR_ENDS_WITH_IGNORE_CASE = 131082,
    DEVPROP_OPERATOR_CONTAINS_IGNORE_CASE = 131083,
    DEVPROP_OPERATOR_LIST_CONTAINS = 4096,
    DEVPROP_OPERATOR_LIST_ELEMENT_BEGINS_WITH = 8192,
    DEVPROP_OPERATOR_LIST_ELEMENT_ENDS_WITH = 12288,
    DEVPROP_OPERATOR_LIST_ELEMENT_CONTAINS = 16384,
    DEVPROP_OPERATOR_LIST_CONTAINS_IGNORE_CASE = 135168,
    DEVPROP_OPERATOR_LIST_ELEMENT_BEGINS_WITH_IGNORE_CASE = 139264,
    DEVPROP_OPERATOR_LIST_ELEMENT_ENDS_WITH_IGNORE_CASE = 143360,
    DEVPROP_OPERATOR_LIST_ELEMENT_CONTAINS_IGNORE_CASE = 147456,
    DEVPROP_OPERATOR_AND_OPEN = 1048576,
    DEVPROP_OPERATOR_AND_CLOSE = 2097152,
    DEVPROP_OPERATOR_OR_OPEN = 3145728,
    DEVPROP_OPERATOR_OR_CLOSE = 4194304,
    DEVPROP_OPERATOR_NOT_OPEN = 5242880,
    DEVPROP_OPERATOR_NOT_CLOSE = 6291456,
    DEVPROP_OPERATOR_ARRAY_CONTAINS = 268435456,
    DEVPROP_OPERATOR_MASK_EVAL = 4095,
    DEVPROP_OPERATOR_MASK_LIST = 61440,
    DEVPROP_OPERATOR_MASK_MODIFIER = 983040,
    DEVPROP_OPERATOR_MASK_NOT_LOGICAL = 4027580415,
    DEVPROP_OPERATOR_MASK_LOGICAL = 267386880,
    DEVPROP_OPERATOR_MASK_ARRAY = 4026531840,
} DEVPROP_OPERATOR;

typedef int DEVPROP_FILTER_EXPRESSION;

typedef enum {
    DevObjectTypeUnknown = 0,
    DevObjectTypeDeviceInterface = 1,
    DevObjectTypeDeviceContainer = 2,
    DevObjectTypeDevice = 3,
    DevObjectTypeDeviceInterfaceClass = 4,
    DevObjectTypeAEP = 5,
    DevObjectTypeAEPContainer = 6,
    DevObjectTypeDeviceInstallerClass = 7,
    DevObjectTypeDeviceInterfaceDisplay = 8,
    DevObjectTypeDeviceContainerDisplay = 9,
    DevObjectTypeAEPService = 10,
    DevObjectTypeDevicePanel = 11,
} DEV_OBJECT_TYPE;

typedef enum {
    DevQueryFlagNone = 0,
    DevQueryFlagUpdateResults = 1,
    DevQueryFlagAllProperties = 2,
    DevQueryFlagLocalize = 4,
    DevQueryFlagAsyncClose = 8,
} DEV_QUERY_FLAGS;

typedef enum {
    DevQueryStateInitialized = 0,
    DevQueryStateEnumCompleted = 1,
    DevQueryStateAborted = 2,
    DevQueryStateClosed = 3,
} DEV_QUERY_STATE;

typedef enum {
    DevQueryResultStateChange = 0,
    DevQueryResultAdd = 1,
    DevQueryResultUpdate = 2,
    DevQueryResultRemove = 3,
} DEV_QUERY_RESULT_ACTION;

typedef int DEV_OBJECT;

typedef int DEV_QUERY_RESULT_ACTION_DATA;

typedef int DEV_QUERY_PARAMETER;

typedef int HDEVQUERY__;

typedef int PDEV_QUERY_RESULT_CALLBACK;


//--------------------------------------------------------------------------------
// Section: Functions (14)
//--------------------------------------------------------------------------------
/*HRESULT*/void DevCreateObjectQuery();

/*HRESULT*/void DevCreateObjectQueryEx();

/*HRESULT*/void DevCreateObjectQueryFromId();

/*HRESULT*/void DevCreateObjectQueryFromIdEx();

/*HRESULT*/void DevCreateObjectQueryFromIds();

/*HRESULT*/void DevCreateObjectQueryFromIdsEx();

/*void*/void DevCloseObjectQuery();

/*HRESULT*/void DevGetObjects();

/*HRESULT*/void DevGetObjectsEx();

/*void*/void DevFreeObjects();

/*HRESULT*/void DevGetObjectProperties();

/*HRESULT*/void DevGetObjectPropertiesEx();

/*void*/void DevFreeObjectProperties();

/*?*DEVPROPERTY*/void DevFindProperty();

