// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (1)
//--------------------------------------------------------------------------------
#define LOCATION_API_VERSION (UINT)1

//--------------------------------------------------------------------------------
// Section: Types (23)
//--------------------------------------------------------------------------------
typedef int Location;

typedef int DefaultLocation;

typedef int LatLongReport;

typedef int CivicAddressReport;

typedef int LatLongReportFactory;

typedef int CivicAddressReportFactory;

typedef int DispLatLongReport;

typedef int DispCivicAddressReport;

typedef enum {
    REPORT_NOT_SUPPORTED = 0,
    REPORT_ERROR = 1,
    REPORT_ACCESS_DENIED = 2,
    REPORT_INITIALIZING = 3,
    REPORT_RUNNING = 4,
} LOCATION_REPORT_STATUS;

// TODO: this type is limited to platform 'windows6.1'
typedef int ILocationReport;

// TODO: this type is limited to platform 'windows6.1'
typedef int ILatLongReport;

// TODO: this type is limited to platform 'windows6.1'
typedef int ICivicAddressReport;

// TODO: this type is limited to platform 'windows6.1'
typedef int ILocation;

// TODO: this type is limited to platform 'windows8.0'
typedef int ILocationPower;

// TODO: this type is limited to platform 'windows6.1'
typedef int IDefaultLocation;

// TODO: this type is limited to platform 'windows6.1'
typedef int ILocationEvents;

typedef int IDispLatLongReport;

typedef int IDispCivicAddressReport;

typedef int ILocationReportFactory;

typedef int ILatLongReportFactory;

typedef int ICivicAddressReportFactory;

typedef int _ILatLongReportFactoryEvents;

typedef int _ICivicAddressReportFactoryEvents;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
