// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (1)
//--------------------------------------------------------------------------------
#define E_UNKNOWNTYPE (HRESULT)(INT)-2144665560

//--------------------------------------------------------------------------------
// Section: Types (21)
//--------------------------------------------------------------------------------
typedef enum {
    Add = 0,
    Remove = 1,
} VisualMutationType;

typedef enum {
    BaseValueSourceUnknown = 0,
    BaseValueSourceDefault = 1,
    BaseValueSourceBuiltInStyle = 2,
    BaseValueSourceStyle = 3,
    BaseValueSourceLocal = 4,
    Inherited = 5,
    DefaultStyleTrigger = 6,
    TemplateTrigger = 7,
    StyleTrigger = 8,
    ImplicitStyleReference = 9,
    ParentTemplate = 10,
    ParentTemplateTrigger = 11,
    Animation = 12,
    Coercion = 13,
    BaseValueSourceVisualState = 14,
} BaseValueSource;

typedef int SourceInfo;

typedef int ParentChildRelation;

typedef int VisualElement;

typedef int PropertyChainSource;

typedef enum {
    None = 0,
    IsValueHandle = 1,
    IsPropertyReadOnly = 2,
    IsValueCollection = 4,
    IsValueCollectionReadOnly = 8,
    IsValueBindingExpression = 16,
    IsValueNull = 32,
    IsValueHandleAndEvaluatedValue = 64,
} MetadataBit;
// NOTE: not creating aliases because this enum is 'Scoped'

typedef int PropertyChainValue;

typedef int EnumType;

typedef int CollectionElementValue;

typedef enum {
    RenderTarget = 0,
    RenderTargetAndChildren = 1,
} RenderTargetBitmapOptions;

typedef int BitmapDescription;

typedef enum {
    ResourceTypeStatic = 0,
    ResourceTypeTheme = 1,
} ResourceType;

typedef enum {
    ErrorResolved = 0,
    ErrorResourceNotFound = 1,
    ErrorInvalidResource = 2,
} VisualElementState;

// TODO: this type is limited to platform 'windows10.0.10240'
typedef int IVisualTreeServiceCallback;

// TODO: this type is limited to platform 'windows10.0.14393'
typedef int IVisualTreeServiceCallback2;

typedef int IVisualTreeService;

// TODO: this type is limited to platform 'windows10.0.10240'
typedef int IXamlDiagnostics;

// TODO: this type is limited to platform 'windows10.0.14393'
typedef int IBitmapData;

// TODO: this type is limited to platform 'windows10.0.14393'
typedef int IVisualTreeService2;

// TODO: this type is limited to platform 'windows10.0.15063'
typedef int IVisualTreeService3;


//--------------------------------------------------------------------------------
// Section: Functions (2)
//--------------------------------------------------------------------------------
/*HRESULT*/void InitializeXamlDiagnostic();

// TODO: this type is limited to platform 'windows10.0.15063'
/*HRESULT*/void InitializeXamlDiagnosticsEx();

