// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (2)
//--------------------------------------------------------------------------------
#define WNV_API_MAJOR_VERSION_1 (UINT)1
#define WNV_API_MINOR_VERSION_0 (UINT)0

//--------------------------------------------------------------------------------
// Section: Types (11)
//--------------------------------------------------------------------------------
typedef enum {
    WnvPolicyMismatchType = 0,
    WnvRedirectType = 1,
    WnvObjectChangeType = 2,
    WnvNotificationTypeMax = 3,
} WNV_NOTIFICATION_TYPE;

typedef enum {
    WnvProviderAddressType = 0,
    WnvCustomerAddressType = 1,
    WnvObjectTypeMax = 2,
} WNV_OBJECT_TYPE;

typedef enum {
    WnvCustomerAddressAdded = 0,
    WnvCustomerAddressDeleted = 1,
    WnvCustomerAddressMoved = 2,
    WnvCustomerAddressMax = 3,
} WNV_CA_NOTIFICATION_TYPE;

typedef int WNV_OBJECT_HEADER;

typedef int WNV_NOTIFICATION_PARAM;

typedef int WNV_IP_ADDRESS;

typedef int WNV_POLICY_MISMATCH_PARAM;

typedef int WNV_PROVIDER_ADDRESS_CHANGE_PARAM;

typedef int WNV_CUSTOMER_ADDRESS_CHANGE_PARAM;

typedef int WNV_OBJECT_CHANGE_PARAM;

typedef int WNV_REDIRECT_PARAM;


//--------------------------------------------------------------------------------
// Section: Functions (2)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windowsServer2012'
/*HANDLE*/void WnvOpen();

// TODO: this type is limited to platform 'windowsServer2012'
/*u32*/void WnvRequestNotification();

