// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (3)
//--------------------------------------------------------------------------------
#define ID_DOCUMENTPACKAGETARGET_MSXPS GUID { "9cae40a8-ded1-41c9-a9fd-d735ef33aeda" }
#define ID_DOCUMENTPACKAGETARGET_OPENXPS GUID { "0056bb72-8c9c-4612-bd0f-93012a87099d" }
#define ID_DOCUMENTPACKAGETARGET_OPENXPS_WITH_3D GUID { "63dbd720-8b14-4577-b074-7bb11b596d28" }

//--------------------------------------------------------------------------------
// Section: Types (11)
//--------------------------------------------------------------------------------
typedef enum {
    XPS_JOB_IN_PROGRESS = 0,
    XPS_JOB_COMPLETED = 1,
    XPS_JOB_CANCELLED = 2,
    XPS_JOB_FAILED = 3,
} XPS_JOB_COMPLETION;

typedef int XPS_JOB_STATUS;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsPrintJobStream;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsPrintJob;

typedef int PrintDocumentPackageTarget;

typedef int PrintDocumentPackageTargetFactory;

// TODO: this type is limited to platform 'windows8.0'
typedef int IPrintDocumentPackageTarget;

typedef enum {
    PrintDocumentPackageCompletion_InProgress = 0,
    PrintDocumentPackageCompletion_Completed = 1,
    PrintDocumentPackageCompletion_Canceled = 2,
    PrintDocumentPackageCompletion_Failed = 3,
} PrintDocumentPackageCompletion;

typedef int PrintDocumentPackageStatus;

// TODO: this type is limited to platform 'windows8.0'
typedef int IPrintDocumentPackageStatusEvent;

// TODO: this type is limited to platform 'windows8.0'
typedef int IPrintDocumentPackageTargetFactory;


//--------------------------------------------------------------------------------
// Section: Functions (2)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void StartXpsPrintJob();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void StartXpsPrintJob1();

