// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Types (7)
//--------------------------------------------------------------------------------
typedef int WindowsMediaLibrarySharingServices;

typedef enum {
    DEVICE_AUTHORIZATION_UNKNOWN = 0,
    DEVICE_AUTHORIZATION_ALLOWED = 1,
    DEVICE_AUTHORIZATION_DENIED = 2,
} WindowsMediaLibrarySharingDeviceAuthorizationStatus;

// TODO: this type is limited to platform 'windows6.1'
typedef int IWindowsMediaLibrarySharingDeviceProperty;

// TODO: this type is limited to platform 'windows6.1'
typedef int IWindowsMediaLibrarySharingDeviceProperties;

// TODO: this type is limited to platform 'windows6.1'
typedef int IWindowsMediaLibrarySharingDevice;

// TODO: this type is limited to platform 'windows6.1'
typedef int IWindowsMediaLibrarySharingDevices;

// TODO: this type is limited to platform 'windows6.1'
typedef int IWindowsMediaLibrarySharingServices;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
