// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Types (31)
//--------------------------------------------------------------------------------
typedef int PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT;

typedef int PRJ_DIR_ENTRY_BUFFER_HANDLE;

typedef enum {
    PRJ_NOTIFY_NONE = 0,
    PRJ_NOTIFY_SUPPRESS_NOTIFICATIONS = 1,
    PRJ_NOTIFY_FILE_OPENED = 2,
    PRJ_NOTIFY_NEW_FILE_CREATED = 4,
    PRJ_NOTIFY_FILE_OVERWRITTEN = 8,
    PRJ_NOTIFY_PRE_DELETE = 16,
    PRJ_NOTIFY_PRE_RENAME = 32,
    PRJ_NOTIFY_PRE_SET_HARDLINK = 64,
    PRJ_NOTIFY_FILE_RENAMED = 128,
    PRJ_NOTIFY_HARDLINK_CREATED = 256,
    PRJ_NOTIFY_FILE_HANDLE_CLOSED_NO_MODIFICATION = 512,
    PRJ_NOTIFY_FILE_HANDLE_CLOSED_FILE_MODIFIED = 1024,
    PRJ_NOTIFY_FILE_HANDLE_CLOSED_FILE_DELETED = 2048,
    PRJ_NOTIFY_FILE_PRE_CONVERT_TO_FULL = 4096,
    PRJ_NOTIFY_USE_EXISTING_MASK = 4294967295,
} PRJ_NOTIFY_TYPES;

typedef enum {
    PRJ_NOTIFICATION_FILE_OPENED = 2,
    PRJ_NOTIFICATION_NEW_FILE_CREATED = 4,
    PRJ_NOTIFICATION_FILE_OVERWRITTEN = 8,
    PRJ_NOTIFICATION_PRE_DELETE = 16,
    PRJ_NOTIFICATION_PRE_RENAME = 32,
    PRJ_NOTIFICATION_PRE_SET_HARDLINK = 64,
    PRJ_NOTIFICATION_FILE_RENAMED = 128,
    PRJ_NOTIFICATION_HARDLINK_CREATED = 256,
    PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_NO_MODIFICATION = 512,
    PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_FILE_MODIFIED = 1024,
    PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_FILE_DELETED = 2048,
    PRJ_NOTIFICATION_FILE_PRE_CONVERT_TO_FULL = 4096,
} PRJ_NOTIFICATION;

typedef enum {
    PRJ_EXT_INFO_TYPE_SYMLINK = 1,
} PRJ_EXT_INFO_TYPE;

typedef int PRJ_EXTENDED_INFO;

typedef int PRJ_NOTIFICATION_MAPPING;

typedef enum {
    PRJ_FLAG_NONE = 0,
    PRJ_FLAG_USE_NEGATIVE_PATH_CACHE = 1,
} PRJ_STARTVIRTUALIZING_FLAGS;

typedef int PRJ_STARTVIRTUALIZING_OPTIONS;

typedef int PRJ_VIRTUALIZATION_INSTANCE_INFO;

typedef enum {
    PRJ_PLACEHOLDER_ID_LENGTH = 128,
} PRJ_PLACEHOLDER_ID;

typedef int PRJ_PLACEHOLDER_VERSION_INFO;

typedef int PRJ_FILE_BASIC_INFO;

typedef int PRJ_PLACEHOLDER_INFO;

typedef enum {
    PRJ_UPDATE_NONE = 0,
    PRJ_UPDATE_ALLOW_DIRTY_METADATA = 1,
    PRJ_UPDATE_ALLOW_DIRTY_DATA = 2,
    PRJ_UPDATE_ALLOW_TOMBSTONE = 4,
    PRJ_UPDATE_RESERVED1 = 8,
    PRJ_UPDATE_RESERVED2 = 16,
    PRJ_UPDATE_ALLOW_READ_ONLY = 32,
    PRJ_UPDATE_MAX_VAL = 64,
} PRJ_UPDATE_TYPES;

typedef enum {
    PRJ_UPDATE_FAILURE_CAUSE_NONE = 0,
    PRJ_UPDATE_FAILURE_CAUSE_DIRTY_METADATA = 1,
    PRJ_UPDATE_FAILURE_CAUSE_DIRTY_DATA = 2,
    PRJ_UPDATE_FAILURE_CAUSE_TOMBSTONE = 4,
    PRJ_UPDATE_FAILURE_CAUSE_READ_ONLY = 8,
} PRJ_UPDATE_FAILURE_CAUSES;

typedef enum {
    PRJ_FILE_STATE_PLACEHOLDER = 1,
    PRJ_FILE_STATE_HYDRATED_PLACEHOLDER = 2,
    PRJ_FILE_STATE_DIRTY_PLACEHOLDER = 4,
    PRJ_FILE_STATE_FULL = 8,
    PRJ_FILE_STATE_TOMBSTONE = 16,
} PRJ_FILE_STATE;

typedef enum {
    PRJ_CB_DATA_FLAG_ENUM_RESTART_SCAN = 1,
    PRJ_CB_DATA_FLAG_ENUM_RETURN_SINGLE_ENTRY = 2,
} PRJ_CALLBACK_DATA_FLAGS;

typedef int PRJ_CALLBACK_DATA;

typedef int PRJ_START_DIRECTORY_ENUMERATION_CB;

typedef int PRJ_GET_DIRECTORY_ENUMERATION_CB;

typedef int PRJ_END_DIRECTORY_ENUMERATION_CB;

typedef int PRJ_GET_PLACEHOLDER_INFO_CB;

typedef int PRJ_GET_FILE_DATA_CB;

typedef int PRJ_QUERY_FILE_NAME_CB;

typedef int PRJ_NOTIFICATION_PARAMETERS;

typedef int PRJ_NOTIFICATION_CB;

typedef int PRJ_CANCEL_COMMAND_CB;

typedef int PRJ_CALLBACKS;

typedef enum {
    PRJ_COMPLETE_COMMAND_TYPE_NOTIFICATION = 1,
    PRJ_COMPLETE_COMMAND_TYPE_ENUMERATION = 2,
} PRJ_COMPLETE_COMMAND_TYPE;

typedef int PRJ_COMPLETE_COMMAND_EXTENDED_PARAMETERS;


//--------------------------------------------------------------------------------
// Section: Functions (19)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjStartVirtualizing();

// TODO: this type is limited to platform 'windows10.0.17763'
/*void*/void PrjStopVirtualizing();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjClearNegativePathCache();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjGetVirtualizationInstanceInfo();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjMarkDirectoryAsPlaceholder();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjWritePlaceholderInfo();

// TODO: this type is limited to platform 'windows10.0.19041'
/*HRESULT*/void PrjWritePlaceholderInfo2();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjUpdateFileIfNeeded();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjDeleteFile();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjWriteFileData();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjGetOnDiskFileState();

// TODO: this type is limited to platform 'windows10.0.17763'
/*?*c_void*/void PrjAllocateAlignedBuffer();

// TODO: this type is limited to platform 'windows10.0.17763'
/*void*/void PrjFreeAlignedBuffer();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjCompleteCommand();

// TODO: this type is limited to platform 'windows10.0.17763'
/*HRESULT*/void PrjFillDirEntryBuffer();

// TODO: this type is limited to platform 'windows10.0.19041'
/*HRESULT*/void PrjFillDirEntryBuffer2();

// TODO: this type is limited to platform 'windows10.0.17763'
/*BOOLEAN*/void PrjFileNameMatch();

// TODO: this type is limited to platform 'windows10.0.17763'
/*i32*/void PrjFileNameCompare();

// TODO: this type is limited to platform 'windows10.0.17763'
/*BOOLEAN*/void PrjDoesNameContainWildCards();

