// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (85)
//--------------------------------------------------------------------------------
#define XPS_E_SIGREQUESTID_DUP (HRESULT)(INT)-2142108795
#define XPS_E_PACKAGE_NOT_OPENED (HRESULT)(INT)-2142108794
#define XPS_E_PACKAGE_ALREADY_OPENED (HRESULT)(INT)-2142108793
#define XPS_E_SIGNATUREID_DUP (HRESULT)(INT)-2142108792
#define XPS_E_MARKUP_COMPATIBILITY_ELEMENTS (HRESULT)(INT)-2142108791
#define XPS_E_OBJECT_DETACHED (HRESULT)(INT)-2142108790
#define XPS_E_INVALID_SIGNATUREBLOCK_MARKUP (HRESULT)(INT)-2142108789
#define XPS_E_INVALID_NUMBER_OF_POINTS_IN_CURVE_SEGMENTS (HRESULT)(INT)-2142108160
#define XPS_E_ABSOLUTE_REFERENCE (HRESULT)(INT)-2142108159
#define XPS_E_INVALID_NUMBER_OF_COLOR_CHANNELS (HRESULT)(INT)-2142108158
#define XPS_E_INVALID_LANGUAGE (HRESULT)(INT)-2142109696
#define XPS_E_INVALID_NAME (HRESULT)(INT)-2142109695
#define XPS_E_INVALID_RESOURCE_KEY (HRESULT)(INT)-2142109694
#define XPS_E_INVALID_PAGE_SIZE (HRESULT)(INT)-2142109693
#define XPS_E_INVALID_BLEED_BOX (HRESULT)(INT)-2142109692
#define XPS_E_INVALID_THUMBNAIL_IMAGE_TYPE (HRESULT)(INT)-2142109691
#define XPS_E_INVALID_LOOKUP_TYPE (HRESULT)(INT)-2142109690
#define XPS_E_INVALID_FLOAT (HRESULT)(INT)-2142109689
#define XPS_E_UNEXPECTED_CONTENT_TYPE (HRESULT)(INT)-2142109688
#define XPS_E_INVALID_FONT_URI (HRESULT)(INT)-2142109686
#define XPS_E_INVALID_CONTENT_BOX (HRESULT)(INT)-2142109685
#define XPS_E_INVALID_MARKUP (HRESULT)(INT)-2142109684
#define XPS_E_INVALID_XML_ENCODING (HRESULT)(INT)-2142109683
#define XPS_E_INVALID_CONTENT_TYPE (HRESULT)(INT)-2142109682
#define XPS_E_INVALID_OBFUSCATED_FONT_URI (HRESULT)(INT)-2142109681
#define XPS_E_UNEXPECTED_RELATIONSHIP_TYPE (HRESULT)(INT)-2142109680
#define XPS_E_UNEXPECTED_RESTRICTED_FONT_RELATIONSHIP (HRESULT)(INT)-2142109679
#define XPS_E_MISSING_NAME (HRESULT)(INT)-2142109440
#define XPS_E_MISSING_LOOKUP (HRESULT)(INT)-2142109439
#define XPS_E_MISSING_GLYPHS (HRESULT)(INT)-2142109438
#define XPS_E_MISSING_SEGMENT_DATA (HRESULT)(INT)-2142109437
#define XPS_E_MISSING_COLORPROFILE (HRESULT)(INT)-2142109436
#define XPS_E_MISSING_RELATIONSHIP_TARGET (HRESULT)(INT)-2142109435
#define XPS_E_MISSING_RESOURCE_RELATIONSHIP (HRESULT)(INT)-2142109434
#define XPS_E_MISSING_FONTURI (HRESULT)(INT)-2142109433
#define XPS_E_MISSING_DOCUMENTSEQUENCE_RELATIONSHIP (HRESULT)(INT)-2142109432
#define XPS_E_MISSING_DOCUMENT (HRESULT)(INT)-2142109431
#define XPS_E_MISSING_REFERRED_DOCUMENT (HRESULT)(INT)-2142109430
#define XPS_E_MISSING_REFERRED_PAGE (HRESULT)(INT)-2142109429
#define XPS_E_MISSING_PAGE_IN_DOCUMENT (HRESULT)(INT)-2142109428
#define XPS_E_MISSING_PAGE_IN_PAGEREFERENCE (HRESULT)(INT)-2142109427
#define XPS_E_MISSING_IMAGE_IN_IMAGEBRUSH (HRESULT)(INT)-2142109426
#define XPS_E_MISSING_RESOURCE_KEY (HRESULT)(INT)-2142109425
#define XPS_E_MISSING_PART_REFERENCE (HRESULT)(INT)-2142109424
#define XPS_E_MISSING_RESTRICTED_FONT_RELATIONSHIP (HRESULT)(INT)-2142109423
#define XPS_E_MISSING_DISCARDCONTROL (HRESULT)(INT)-2142109422
#define XPS_E_MISSING_PART_STREAM (HRESULT)(INT)-2142109421
#define XPS_E_UNAVAILABLE_PACKAGE (HRESULT)(INT)-2142109420
#define XPS_E_DUPLICATE_RESOURCE_KEYS (HRESULT)(INT)-2142109184
#define XPS_E_MULTIPLE_RESOURCES (HRESULT)(INT)-2142109183
#define XPS_E_MULTIPLE_DOCUMENTSEQUENCE_RELATIONSHIPS (HRESULT)(INT)-2142109182
#define XPS_E_MULTIPLE_THUMBNAILS_ON_PAGE (HRESULT)(INT)-2142109181
#define XPS_E_MULTIPLE_THUMBNAILS_ON_PACKAGE (HRESULT)(INT)-2142109180
#define XPS_E_MULTIPLE_PRINTTICKETS_ON_PAGE (HRESULT)(INT)-2142109179
#define XPS_E_MULTIPLE_PRINTTICKETS_ON_DOCUMENT (HRESULT)(INT)-2142109178
#define XPS_E_MULTIPLE_PRINTTICKETS_ON_DOCUMENTSEQUENCE (HRESULT)(INT)-2142109177
#define XPS_E_MULTIPLE_REFERENCES_TO_PART (HRESULT)(INT)-2142109176
#define XPS_E_DUPLICATE_NAMES (HRESULT)(INT)-2142109175
#define XPS_E_STRING_TOO_LONG (HRESULT)(INT)-2142108928
#define XPS_E_TOO_MANY_INDICES (HRESULT)(INT)-2142108927
#define XPS_E_MAPPING_OUT_OF_ORDER (HRESULT)(INT)-2142108926
#define XPS_E_MAPPING_OUTSIDE_STRING (HRESULT)(INT)-2142108925
#define XPS_E_MAPPING_OUTSIDE_INDICES (HRESULT)(INT)-2142108924
#define XPS_E_CARET_OUTSIDE_STRING (HRESULT)(INT)-2142108923
#define XPS_E_CARET_OUT_OF_ORDER (HRESULT)(INT)-2142108922
#define XPS_E_ODD_BIDILEVEL (HRESULT)(INT)-2142108921
#define XPS_E_ONE_TO_ONE_MAPPING_EXPECTED (HRESULT)(INT)-2142108920
#define XPS_E_RESTRICTED_FONT_NOT_OBFUSCATED (HRESULT)(INT)-2142108919
#define XPS_E_NEGATIVE_FLOAT (HRESULT)(INT)-2142108918
#define XPS_E_XKEY_ATTR_PRESENT_OUTSIDE_RES_DICT (HRESULT)(INT)-2142108672
#define XPS_E_DICTIONARY_ITEM_NAMED (HRESULT)(INT)-2142108671
#define XPS_E_NESTED_REMOTE_DICTIONARY (HRESULT)(INT)-2142108670
#define XPS_E_INDEX_OUT_OF_RANGE (HRESULT)(INT)-2142108416
#define XPS_E_VISUAL_CIRCULAR_REF (HRESULT)(INT)-2142108415
#define XPS_E_NO_CUSTOM_OBJECTS (HRESULT)(INT)-2142108414
#define XPS_E_ALREADY_OWNED (HRESULT)(INT)-2142108413
#define XPS_E_RESOURCE_NOT_OWNED (HRESULT)(INT)-2142108412
#define XPS_E_UNEXPECTED_COLORPROFILE (HRESULT)(INT)-2142108411
#define XPS_E_COLOR_COMPONENT_OUT_OF_RANGE (HRESULT)(INT)-2142108410
#define XPS_E_BOTH_PATHFIGURE_AND_ABBR_SYNTAX_PRESENT (HRESULT)(INT)-2142108409
#define XPS_E_BOTH_RESOURCE_AND_SOURCEATTR_PRESENT (HRESULT)(INT)-2142108408
#define XPS_E_BLEED_BOX_PAGE_DIMENSIONS_NOT_IN_SYNC (HRESULT)(INT)-2142108407
#define XPS_E_RELATIONSHIP_EXTERNAL (HRESULT)(INT)-2142108406
#define XPS_E_NOT_ENOUGH_GRADIENT_STOPS (HRESULT)(INT)-2142108405
#define XPS_E_PACKAGE_WRITER_NOT_CLOSED (HRESULT)(INT)-2142108404

//--------------------------------------------------------------------------------
// Section: Types (110)
//--------------------------------------------------------------------------------
typedef enum {
    PW_CLIENTONLY = 1,
} PRINT_WINDOW_FLAGS;

typedef enum {
    DC_BINNAMES = 12,
    DC_BINS = 6,
    DC_COLLATE = 22,
    DC_COLORDEVICE = 32,
    DC_COPIES = 18,
    DC_DRIVER = 11,
    DC_DUPLEX = 7,
    DC_ENUMRESOLUTIONS = 13,
    DC_EXTRA = 9,
    DC_FIELDS = 1,
    DC_FILEDEPENDENCIES = 14,
    DC_MAXEXTENT = 5,
    DC_MEDIAREADY = 29,
    DC_MEDIATYPENAMES = 34,
    DC_MEDIATYPES = 35,
    DC_MINEXTENT = 4,
    DC_ORIENTATION = 17,
    DC_NUP = 33,
    DC_PAPERNAMES = 16,
    DC_PAPERS = 2,
    DC_PAPERSIZE = 3,
    DC_PERSONALITY = 25,
    DC_PRINTERMEM = 28,
    DC_PRINTRATE = 26,
    DC_PRINTRATEPPM = 31,
    DC_PRINTRATEUNIT = 27,
    DC_SIZE = 8,
    DC_STAPLE = 30,
    DC_TRUETYPE = 15,
    DC_VERSION = 10,
} DEVICE_CAPABILITIES;

typedef enum {
    PSINJECT_BEGINSTREAM = 1,
    PSINJECT_PSADOBE = 2,
    PSINJECT_PAGESATEND = 3,
    PSINJECT_PAGES = 4,
    PSINJECT_DOCNEEDEDRES = 5,
    PSINJECT_DOCSUPPLIEDRES = 6,
    PSINJECT_PAGEORDER = 7,
    PSINJECT_ORIENTATION = 8,
    PSINJECT_BOUNDINGBOX = 9,
    PSINJECT_DOCUMENTPROCESSCOLORS = 10,
    PSINJECT_COMMENTS = 11,
    PSINJECT_BEGINDEFAULTS = 12,
    PSINJECT_ENDDEFAULTS = 13,
    PSINJECT_BEGINPROLOG = 14,
    PSINJECT_ENDPROLOG = 15,
    PSINJECT_BEGINSETUP = 16,
    PSINJECT_ENDSETUP = 17,
    PSINJECT_TRAILER = 18,
    PSINJECT_EOF = 19,
    PSINJECT_ENDSTREAM = 20,
    PSINJECT_DOCUMENTPROCESSCOLORSATEND = 21,
    PSINJECT_PAGENUMBER = 100,
    PSINJECT_BEGINPAGESETUP = 101,
    PSINJECT_ENDPAGESETUP = 102,
    PSINJECT_PAGETRAILER = 103,
    PSINJECT_PLATECOLOR = 104,
    PSINJECT_SHOWPAGE = 105,
    PSINJECT_PAGEBBOX = 106,
    PSINJECT_ENDPAGECOMMENTS = 107,
    PSINJECT_VMSAVE = 200,
    PSINJECT_VMRESTORE = 201,
} PSINJECT_POINT;

typedef int HPTPROVIDER;

typedef int DRAWPATRECT;

typedef int PSINJECTDATA;

typedef int PSFEATURE_OUTPUT;

typedef int PSFEATURE_CUSTPAPER;

typedef int ABORTPROC;

typedef int DOCINFOA;

typedef int DOCINFOW;

typedef int XpsOMObjectFactory;

typedef int XpsOMThumbnailGenerator;

typedef enum {
    XPS_TILE_MODE_NONE = 1,
    XPS_TILE_MODE_TILE = 2,
    XPS_TILE_MODE_FLIPX = 3,
    XPS_TILE_MODE_FLIPY = 4,
    XPS_TILE_MODE_FLIPXY = 5,
} XPS_TILE_MODE;

typedef enum {
    XPS_COLOR_INTERPOLATION_SCRGBLINEAR = 1,
    XPS_COLOR_INTERPOLATION_SRGBLINEAR = 2,
} XPS_COLOR_INTERPOLATION;

typedef enum {
    XPS_SPREAD_METHOD_PAD = 1,
    XPS_SPREAD_METHOD_REFLECT = 2,
    XPS_SPREAD_METHOD_REPEAT = 3,
} XPS_SPREAD_METHOD;

typedef enum {
    XPS_STYLE_SIMULATION_NONE = 1,
    XPS_STYLE_SIMULATION_ITALIC = 2,
    XPS_STYLE_SIMULATION_BOLD = 3,
    XPS_STYLE_SIMULATION_BOLDITALIC = 4,
} XPS_STYLE_SIMULATION;

typedef enum {
    XPS_LINE_CAP_FLAT = 1,
    XPS_LINE_CAP_ROUND = 2,
    XPS_LINE_CAP_SQUARE = 3,
    XPS_LINE_CAP_TRIANGLE = 4,
} XPS_LINE_CAP;

typedef enum {
    XPS_DASH_CAP_FLAT = 1,
    XPS_DASH_CAP_ROUND = 2,
    XPS_DASH_CAP_SQUARE = 3,
    XPS_DASH_CAP_TRIANGLE = 4,
} XPS_DASH_CAP;

typedef enum {
    XPS_LINE_JOIN_MITER = 1,
    XPS_LINE_JOIN_BEVEL = 2,
    XPS_LINE_JOIN_ROUND = 3,
} XPS_LINE_JOIN;

typedef enum {
    XPS_IMAGE_TYPE_JPEG = 1,
    XPS_IMAGE_TYPE_PNG = 2,
    XPS_IMAGE_TYPE_TIFF = 3,
    XPS_IMAGE_TYPE_WDP = 4,
    XPS_IMAGE_TYPE_JXR = 5,
} XPS_IMAGE_TYPE;

typedef enum {
    XPS_COLOR_TYPE_SRGB = 1,
    XPS_COLOR_TYPE_SCRGB = 2,
    XPS_COLOR_TYPE_CONTEXT = 3,
} XPS_COLOR_TYPE;

typedef enum {
    XPS_FILL_RULE_EVENODD = 1,
    XPS_FILL_RULE_NONZERO = 2,
} XPS_FILL_RULE;

typedef enum {
    XPS_SEGMENT_TYPE_ARC_LARGE_CLOCKWISE = 1,
    XPS_SEGMENT_TYPE_ARC_LARGE_COUNTERCLOCKWISE = 2,
    XPS_SEGMENT_TYPE_ARC_SMALL_CLOCKWISE = 3,
    XPS_SEGMENT_TYPE_ARC_SMALL_COUNTERCLOCKWISE = 4,
    XPS_SEGMENT_TYPE_BEZIER = 5,
    XPS_SEGMENT_TYPE_LINE = 6,
    XPS_SEGMENT_TYPE_QUADRATIC_BEZIER = 7,
} XPS_SEGMENT_TYPE;

typedef enum {
    XPS_SEGMENT_STROKE_PATTERN_ALL = 1,
    XPS_SEGMENT_STROKE_PATTERN_NONE = 2,
    XPS_SEGMENT_STROKE_PATTERN_MIXED = 3,
} XPS_SEGMENT_STROKE_PATTERN;

typedef enum {
    XPS_FONT_EMBEDDING_NORMAL = 1,
    XPS_FONT_EMBEDDING_OBFUSCATED = 2,
    XPS_FONT_EMBEDDING_RESTRICTED = 3,
    XPS_FONT_EMBEDDING_RESTRICTED_UNOBFUSCATED = 4,
} XPS_FONT_EMBEDDING;

typedef enum {
    XPS_OBJECT_TYPE_CANVAS = 1,
    XPS_OBJECT_TYPE_GLYPHS = 2,
    XPS_OBJECT_TYPE_PATH = 3,
    XPS_OBJECT_TYPE_MATRIX_TRANSFORM = 4,
    XPS_OBJECT_TYPE_GEOMETRY = 5,
    XPS_OBJECT_TYPE_SOLID_COLOR_BRUSH = 6,
    XPS_OBJECT_TYPE_IMAGE_BRUSH = 7,
    XPS_OBJECT_TYPE_LINEAR_GRADIENT_BRUSH = 8,
    XPS_OBJECT_TYPE_RADIAL_GRADIENT_BRUSH = 9,
    XPS_OBJECT_TYPE_VISUAL_BRUSH = 10,
} XPS_OBJECT_TYPE;

typedef enum {
    XPS_THUMBNAIL_SIZE_VERYSMALL = 1,
    XPS_THUMBNAIL_SIZE_SMALL = 2,
    XPS_THUMBNAIL_SIZE_MEDIUM = 3,
    XPS_THUMBNAIL_SIZE_LARGE = 4,
} XPS_THUMBNAIL_SIZE;

typedef enum {
    XPS_INTERLEAVING_OFF = 1,
    XPS_INTERLEAVING_ON = 2,
} XPS_INTERLEAVING;

typedef int XPS_POINT;

typedef int XPS_SIZE;

typedef int XPS_RECT;

typedef int XPS_DASH;

typedef int XPS_GLYPH_INDEX;

typedef int XPS_GLYPH_MAPPING;

typedef int XPS_MATRIX;

typedef int XPS_COLOR;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMShareable;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMVisual;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPart;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGlyphsEditor;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGlyphs;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMDashCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMMatrixTransform;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGeometry;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGeometryFigure;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGeometryFigureCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPath;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGradientStopCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMSolidColorBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMTileBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMVisualBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMImageBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGradientStop;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMGradientBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMLinearGradientBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMRadialGradientBrush;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPartResources;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMDictionary;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMFontResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMFontResourceCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMImageResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMImageResourceCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMColorProfileResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMColorProfileResourceCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPrintTicketResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMRemoteDictionaryResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMRemoteDictionaryResourceCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMSignatureBlockResourceCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMDocumentStructureResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMStoryFragmentsResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMSignatureBlockResource;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMVisualCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMCanvas;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPage;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPageReference;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPageReferenceCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMDocument;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMDocumentCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMDocumentSequence;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMCoreProperties;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPackage;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMObjectFactory;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMNameCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPartUriCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPackageWriter;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMPackageTarget;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsOMThumbnailGenerator;

typedef enum {
    XPS_DOCUMENT_TYPE_UNSPECIFIED = 1,
    XPS_DOCUMENT_TYPE_XPS = 2,
    XPS_DOCUMENT_TYPE_OPENXPS = 3,
} XPS_DOCUMENT_TYPE;

// TODO: this type is limited to platform 'windows8.0'
typedef int IXpsOMObjectFactory1;

// TODO: this type is limited to platform 'windows8.0'
typedef int IXpsOMPackage1;

// TODO: this type is limited to platform 'windows8.0'
typedef int IXpsOMPage1;

// TODO: this type is limited to platform 'windows8.0'
typedef int IXpsDocumentPackageTarget;

// TODO: this type is limited to platform 'windows8.0'
typedef int IXpsOMRemoteDictionaryResource1;

// TODO: this type is limited to platform 'windows8.1'
typedef int IXpsOMPackageWriter3D;

// TODO: this type is limited to platform 'windows8.1'
typedef int IXpsDocumentPackageTarget3D;

typedef int XpsSignatureManager;

typedef enum {
    XPS_SIGNATURE_STATUS_INCOMPLIANT = 1,
    XPS_SIGNATURE_STATUS_INCOMPLETE = 2,
    XPS_SIGNATURE_STATUS_BROKEN = 3,
    XPS_SIGNATURE_STATUS_QUESTIONABLE = 4,
    XPS_SIGNATURE_STATUS_VALID = 5,
} XPS_SIGNATURE_STATUS;

typedef enum {
    XPS_SIGN_POLICY_NONE = 0,
    XPS_SIGN_POLICY_CORE_PROPERTIES = 1,
    XPS_SIGN_POLICY_SIGNATURE_RELATIONSHIPS = 2,
    XPS_SIGN_POLICY_PRINT_TICKET = 4,
    XPS_SIGN_POLICY_DISCARD_CONTROL = 8,
    XPS_SIGN_POLICY_ALL = 15,
} XPS_SIGN_POLICY;

typedef enum {
    XPS_SIGN_FLAGS_NONE = 0,
    XPS_SIGN_FLAGS_IGNORE_MARKUP_COMPATIBILITY = 1,
} XPS_SIGN_FLAGS;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSigningOptions;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignatureCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignature;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignatureBlockCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignatureBlock;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignatureRequestCollection;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignatureRequest;

// TODO: this type is limited to platform 'windows6.1'
typedef int IXpsSignatureManager;


//--------------------------------------------------------------------------------
// Section: Functions (12)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.0'
/*i32*/void DeviceCapabilitiesA();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void DeviceCapabilitiesW();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void Escape();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void ExtEscape();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void StartDocA();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void StartDocW();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void EndDoc();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void StartPage();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void EndPage();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void AbortDoc();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void SetAbortProc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void PrintWindow();

