// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (45)
//--------------------------------------------------------------------------------
#define UPNP_E_ROOT_ELEMENT_EXPECTED (HRESULT)(INT)-2147220992
#define UPNP_E_DEVICE_ELEMENT_EXPECTED (HRESULT)(INT)-2147220991
#define UPNP_E_SERVICE_ELEMENT_EXPECTED (HRESULT)(INT)-2147220990
#define UPNP_E_SERVICE_NODE_INCOMPLETE (HRESULT)(INT)-2147220989
#define UPNP_E_DEVICE_NODE_INCOMPLETE (HRESULT)(INT)-2147220988
#define UPNP_E_ICON_ELEMENT_EXPECTED (HRESULT)(INT)-2147220987
#define UPNP_E_ICON_NODE_INCOMPLETE (HRESULT)(INT)-2147220986
#define UPNP_E_INVALID_ACTION (HRESULT)(INT)-2147220985
#define UPNP_E_INVALID_ARGUMENTS (HRESULT)(INT)-2147220984
#define UPNP_E_OUT_OF_SYNC (HRESULT)(INT)-2147220983
#define UPNP_E_ACTION_REQUEST_FAILED (HRESULT)(INT)-2147220976
#define UPNP_E_TRANSPORT_ERROR (HRESULT)(INT)-2147220975
#define UPNP_E_VARIABLE_VALUE_UNKNOWN (HRESULT)(INT)-2147220974
#define UPNP_E_INVALID_VARIABLE (HRESULT)(INT)-2147220973
#define UPNP_E_DEVICE_ERROR (HRESULT)(INT)-2147220972
#define UPNP_E_PROTOCOL_ERROR (HRESULT)(INT)-2147220971
#define UPNP_E_ERROR_PROCESSING_RESPONSE (HRESULT)(INT)-2147220970
#define UPNP_E_DEVICE_TIMEOUT (HRESULT)(INT)-2147220969
#define UPNP_E_INVALID_DOCUMENT (HRESULT)(INT)-2147220224
#define UPNP_E_EVENT_SUBSCRIPTION_FAILED (HRESULT)(INT)-2147220223
#define FAULT_INVALID_ACTION (UINT)401
#define FAULT_INVALID_ARG (UINT)402
#define FAULT_INVALID_SEQUENCE_NUMBER (UINT)403
#define FAULT_INVALID_VARIABLE (UINT)404
#define FAULT_DEVICE_INTERNAL_ERROR (UINT)501
#define FAULT_ACTION_SPECIFIC_BASE (UINT)600
#define FAULT_ACTION_SPECIFIC_MAX (UINT)899
#define UPNP_E_ACTION_SPECIFIC_BASE (HRESULT)(INT)-2147220736
#define UPNP_ADDRESSFAMILY_IPv4 (UINT)1
#define UPNP_ADDRESSFAMILY_IPv6 (UINT)2
#define UPNP_ADDRESSFAMILY_BOTH (UINT)3
#define UPNP_SERVICE_DELAY_SCPD_AND_SUBSCRIPTION (UINT)1
#define UPNP_E_REQUIRED_ELEMENT_ERROR (HRESULT)(INT)-2147180512
#define UPNP_E_DUPLICATE_NOT_ALLOWED (HRESULT)(INT)-2147180511
#define UPNP_E_DUPLICATE_SERVICE_ID (HRESULT)(INT)-2147180510
#define UPNP_E_INVALID_DESCRIPTION (HRESULT)(INT)-2147180509
#define UPNP_E_INVALID_SERVICE (HRESULT)(INT)-2147180508
#define UPNP_E_INVALID_ICON (HRESULT)(INT)-2147180507
#define UPNP_E_INVALID_XML (HRESULT)(INT)-2147180506
#define UPNP_E_INVALID_ROOT_NAMESPACE (HRESULT)(INT)-2147180505
#define UPNP_E_SUFFIX_TOO_LONG (HRESULT)(INT)-2147180504
#define UPNP_E_URLBASE_PRESENT (HRESULT)(INT)-2147180503
#define UPNP_E_VALUE_TOO_LONG (HRESULT)(INT)-2147180496
#define UPNP_E_DEVICE_RUNNING (HRESULT)(INT)-2147180495
#define UPNP_E_DEVICE_NOTREGISTERED (HRESULT)(INT)-2147180494

//--------------------------------------------------------------------------------
// Section: Types (41)
//--------------------------------------------------------------------------------
typedef int HSWDEVICE;

typedef enum {
    SWDeviceCapabilitiesNone = 0,
    SWDeviceCapabilitiesRemovable = 1,
    SWDeviceCapabilitiesSilentInstall = 2,
    SWDeviceCapabilitiesNoDisplayInUI = 4,
    SWDeviceCapabilitiesDriverRequired = 8,
} SW_DEVICE_CAPABILITIES;

typedef int SW_DEVICE_CREATE_INFO;

typedef enum {
    SWDeviceLifetimeHandle = 0,
    SWDeviceLifetimeParentPresent = 1,
    SWDeviceLifetimeMax = 2,
} SW_DEVICE_LIFETIME;

typedef int SW_DEVICE_CREATE_CALLBACK;

typedef int UPnPDeviceFinder;

typedef int UPnPDevices;

typedef int UPnPDevice;

typedef int UPnPServices;

typedef int UPnPService;

typedef int UPnPDescriptionDocument;

typedef int UPnPDeviceFinderEx;

typedef int UPnPDescriptionDocumentEx;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDeviceFinder;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IUPnPAddressFamilyControl;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUPnPHttpHeaderControl;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDeviceFinderCallback;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPServices;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPService;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUPnPAsyncResult;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUPnPServiceAsync;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPServiceCallback;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUPnPServiceEnumProperty;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUPnPServiceDocumentAccess;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDevices;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDevice;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDeviceDocumentAccess;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUPnPDeviceDocumentAccessEx;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDescriptionDocument;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IUPnPDeviceFinderAddCallbackWithInterface;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDescriptionDocumentCallback;

typedef int UPnPRegistrar;

typedef int UPnPRemoteEndpointInfo;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPEventSink;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPEventSource;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPRegistrar;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPReregistrar;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDeviceControl;

typedef int IUPnPDeviceControlHttpHeaders;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IUPnPDeviceProvider;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IUPnPRemoteEndpointInfo;


//--------------------------------------------------------------------------------
// Section: Functions (9)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SwDeviceCreate();

// TODO: this type is limited to platform 'windows8.0'
/*void*/void SwDeviceClose();

// TODO: this type is limited to platform 'windows8.1'
/*HRESULT*/void SwDeviceSetLifetime();

// TODO: this type is limited to platform 'windows8.1'
/*HRESULT*/void SwDeviceGetLifetime();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SwDevicePropertySet();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SwDeviceInterfaceRegister();

// TODO: this type is limited to platform 'windows8.0'
/*void*/void SwMemFree();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SwDeviceInterfaceSetState();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SwDeviceInterfacePropertySet();

