// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (2)
//--------------------------------------------------------------------------------
#define NLM_MAX_ADDRESS_LIST_SIZE (UINT)10
#define NLM_UNKNOWN_DATAPLAN_STATUS (UINT)4294967295

//--------------------------------------------------------------------------------
// Section: Types (26)
//--------------------------------------------------------------------------------
typedef int NetworkListManager;

typedef enum {
    NLM_CONNECTION_COST_UNKNOWN = 0,
    NLM_CONNECTION_COST_UNRESTRICTED = 1,
    NLM_CONNECTION_COST_FIXED = 2,
    NLM_CONNECTION_COST_VARIABLE = 4,
    NLM_CONNECTION_COST_OVERDATALIMIT = 65536,
    NLM_CONNECTION_COST_CONGESTED = 131072,
    NLM_CONNECTION_COST_ROAMING = 262144,
    NLM_CONNECTION_COST_APPROACHINGDATALIMIT = 524288,
} NLM_CONNECTION_COST;

typedef int NLM_USAGE_DATA;

typedef int NLM_DATAPLAN_STATUS;

typedef int NLM_SOCKADDR;

typedef enum {
    NLM_NETWORK_IDENTIFYING = 1,
    NLM_NETWORK_IDENTIFIED = 2,
    NLM_NETWORK_UNIDENTIFIED = 3,
} NLM_NETWORK_CLASS;

typedef int NLM_SIMULATED_PROFILE_INFO;

typedef enum {
    NLM_INTERNET_CONNECTIVITY_WEBHIJACK = 1,
    NLM_INTERNET_CONNECTIVITY_PROXIED = 2,
    NLM_INTERNET_CONNECTIVITY_CORPORATE = 4,
} NLM_INTERNET_CONNECTIVITY;

typedef enum {
    NLM_CONNECTIVITY_DISCONNECTED = 0,
    NLM_CONNECTIVITY_IPV4_NOTRAFFIC = 1,
    NLM_CONNECTIVITY_IPV6_NOTRAFFIC = 2,
    NLM_CONNECTIVITY_IPV4_SUBNET = 16,
    NLM_CONNECTIVITY_IPV4_LOCALNETWORK = 32,
    NLM_CONNECTIVITY_IPV4_INTERNET = 64,
    NLM_CONNECTIVITY_IPV6_SUBNET = 256,
    NLM_CONNECTIVITY_IPV6_LOCALNETWORK = 512,
    NLM_CONNECTIVITY_IPV6_INTERNET = 1024,
} NLM_CONNECTIVITY;

typedef enum {
    NLM_DOMAIN_TYPE_NON_DOMAIN_NETWORK = 0,
    NLM_DOMAIN_TYPE_DOMAIN_NETWORK = 1,
    NLM_DOMAIN_TYPE_DOMAIN_AUTHENTICATED = 2,
} NLM_DOMAIN_TYPE;

typedef enum {
    NLM_ENUM_NETWORK_CONNECTED = 1,
    NLM_ENUM_NETWORK_DISCONNECTED = 2,
    NLM_ENUM_NETWORK_ALL = 3,
} NLM_ENUM_NETWORK;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INetworkListManager;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INetworkListManagerEvents;

typedef enum {
    NLM_NETWORK_CATEGORY_PUBLIC = 0,
    NLM_NETWORK_CATEGORY_PRIVATE = 1,
    NLM_NETWORK_CATEGORY_DOMAIN_AUTHENTICATED = 2,
} NLM_NETWORK_CATEGORY;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INetwork;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IEnumNetworks;

typedef enum {
    NLM_NETWORK_PROPERTY_CHANGE_CONNECTION = 1,
    NLM_NETWORK_PROPERTY_CHANGE_DESCRIPTION = 2,
    NLM_NETWORK_PROPERTY_CHANGE_NAME = 4,
    NLM_NETWORK_PROPERTY_CHANGE_ICON = 8,
    NLM_NETWORK_PROPERTY_CHANGE_CATEGORY_VALUE = 16,
} NLM_NETWORK_PROPERTY_CHANGE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INetworkEvents;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INetworkConnection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IEnumNetworkConnections;

typedef enum {
    NLM_CONNECTION_PROPERTY_CHANGE_AUTHENTICATION = 1,
} NLM_CONNECTION_PROPERTY_CHANGE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INetworkConnectionEvents;

// TODO: this type is limited to platform 'windows8.0'
typedef int INetworkCostManager;

// TODO: this type is limited to platform 'windows8.0'
typedef int INetworkCostManagerEvents;

// TODO: this type is limited to platform 'windows8.0'
typedef int INetworkConnectionCost;

// TODO: this type is limited to platform 'windows8.0'
typedef int INetworkConnectionCostEvents;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
