// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (46)
//--------------------------------------------------------------------------------
#define PROP_ID_SECURE_MIN (UINT)26608
#define PROP_ID_SECURE_MAX (UINT)26623
#define MAPI_DIM (UINT)1
#define MAPI_P1 (UINT)268435456
#define MAPI_SUBMITTED (UINT)2147483648
#define MAPI_SHORTTERM (UINT)128
#define MAPI_NOTRECIP (UINT)64
#define MAPI_THISSESSION (UINT)32
#define MAPI_NOW (UINT)16
#define MAPI_NOTRESERVED (UINT)8
#define MAPI_COMPOUND (UINT)128
#define MV_FLAG (UINT)4096
#define PROP_ID_NULL (UINT)0
#define PROP_ID_INVALID (UINT)65535
#define MV_INSTANCE (UINT)8192
#define TABLE_CHANGED (UINT)1
#define TABLE_ERROR (UINT)2
#define TABLE_ROW_ADDED (UINT)3
#define TABLE_ROW_DELETED (UINT)4
#define TABLE_ROW_MODIFIED (UINT)5
#define TABLE_SORT_DONE (UINT)6
#define TABLE_RESTRICT_DONE (UINT)7
#define TABLE_SETCOL_DONE (UINT)8
#define TABLE_RELOAD (UINT)9
#define MAPI_ERROR_VERSION (INT)0
#define MAPI_USE_DEFAULT (UINT)64
#define MNID_ID (UINT)0
#define MNID_STRING (UINT)1
#define WAB_LOCAL_CONTAINERS (UINT)1048576
#define WAB_PROFILE_CONTENTS (UINT)2097152
#define WAB_IGNORE_PROFILES (UINT)8388608
#define MAPI_ONE_OFF_NO_RICH_INFO (UINT)1
#define UI_SERVICE (UINT)2
#define SERVICE_UI_ALWAYS (UINT)2
#define SERVICE_UI_ALLOWED (UINT)16
#define UI_CURRENT_PROVIDER_FIRST (UINT)4
#define WABOBJECT_LDAPURL_RETURN_MAILUSER (UINT)1
#define WABOBJECT_ME_NEW (UINT)1
#define WABOBJECT_ME_NOCREATE (UINT)2
#define WAB_VCARD_FILE (UINT)0
#define WAB_VCARD_STREAM (UINT)1
#define WAB_USE_OE_SENDMAIL (UINT)1
#define WAB_ENABLE_PROFILES (UINT)4194304
#define WAB_DISPLAY_LDAPURL (UINT)1
#define WAB_CONTEXT_ADRLIST (UINT)2
#define WAB_DISPLAY_ISNTDS (UINT)4

//--------------------------------------------------------------------------------
// Section: Types (115)
//--------------------------------------------------------------------------------
typedef int _WABACTIONITEM;

typedef int ENTRYID;

typedef int MAPIUID;

typedef int SPropTagArray;

typedef int SBinary;

typedef int SShortArray;

typedef int SGuidArray;

typedef int SRealArray;

typedef int SLongArray;

typedef int SLargeIntegerArray;

typedef int SDateTimeArray;

typedef int SAppTimeArray;

typedef int SCurrencyArray;

typedef int SBinaryArray;

typedef int SDoubleArray;

typedef int SWStringArray;

typedef int SLPSTRArray;

typedef int _PV;

typedef int SPropValue;

typedef int SPropProblem;

typedef int SPropProblemArray;

typedef int FLATENTRY;

typedef int FLATENTRYLIST;

typedef int MTSID;

typedef int FLATMTSIDLIST;

typedef int ADRENTRY;

typedef int ADRLIST;

typedef int SRow;

typedef int SRowSet;

typedef int LPALLOCATEBUFFER;

typedef int LPALLOCATEMORE;

typedef int LPFREEBUFFER;

typedef int MAPIERROR;

typedef int ERROR_NOTIFICATION;

typedef int NEWMAIL_NOTIFICATION;

typedef int OBJECT_NOTIFICATION;

typedef int TABLE_NOTIFICATION;

typedef int EXTENDED_NOTIFICATION;

typedef int STATUS_OBJECT_NOTIFICATION;

typedef int NOTIFICATION;

typedef int IMAPIAdviseSink;

typedef int LPNOTIFCALLBACK;

typedef int IMAPIProgress;

typedef int MAPINAMEID;

typedef int IMAPIProp;

typedef int SSortOrder;

typedef int SSortOrderSet;

typedef int SAndRestriction;

typedef int SOrRestriction;

typedef int SNotRestriction;

typedef int SContentRestriction;

typedef int SBitMaskRestriction;

typedef int SPropertyRestriction;

typedef int SComparePropsRestriction;

typedef int SSizeRestriction;

typedef int SExistRestriction;

typedef int SSubRestriction;

typedef int SCommentRestriction;

typedef int SRestriction;

// TODO: this type is limited to platform 'windows5.0'
typedef int IMAPITable;

typedef int IProfSect;

typedef int IMAPIStatus;

typedef int IMAPIContainer;

typedef int _flaglist;

// TODO: this type is limited to platform 'windows5.0'
typedef int IABContainer;

// TODO: this type is limited to platform 'windows5.0'
typedef int IMailUser;

// TODO: this type is limited to platform 'windows5.0'
typedef int IDistList;

typedef int IMAPIFolder;

typedef int IMsgStore;

typedef int IMessage;

typedef int IAttach;

typedef int LPFNABSDI;

typedef int LPFNDISMISS;

typedef int LPFNBUTTON;

typedef int ADRPARM;

typedef int IMAPIControl;

typedef int DTBLLABEL;

typedef int DTBLEDIT;

typedef int DTBLLBX;

typedef int DTBLCOMBOBOX;

typedef int DTBLDDLBX;

typedef int DTBLCHECKBOX;

typedef int DTBLGROUPBOX;

typedef int DTBLBUTTON;

typedef int DTBLPAGE;

typedef int DTBLRADIOBUTTON;

typedef int DTBLMVLISTBOX;

typedef int DTBLMVDDLBX;

typedef int IProviderAdmin;

// TODO: this type is limited to platform 'windows5.0'
typedef int IAddrBook;

// TODO: this type is limited to platform 'windows5.0'
typedef int IWABObject;

typedef int IWABOBJECT_QueryInterface_METHOD;

typedef int IWABOBJECT_AddRef_METHOD;

typedef int IWABOBJECT_Release_METHOD;

typedef int IWABOBJECT_GetLastError_METHOD;

typedef int IWABOBJECT_AllocateBuffer_METHOD;

typedef int IWABOBJECT_AllocateMore_METHOD;

typedef int IWABOBJECT_FreeBuffer_METHOD;

typedef int IWABOBJECT_Backup_METHOD;

typedef int IWABOBJECT_Import_METHOD;

typedef int IWABOBJECT_Find_METHOD;

typedef int IWABOBJECT_VCardDisplay_METHOD;

typedef int IWABOBJECT_LDAPUrl_METHOD;

typedef int IWABOBJECT_VCardCreate_METHOD;

typedef int IWABOBJECT_VCardRetrieve_METHOD;

typedef int IWABOBJECT_GetMe_METHOD;

typedef int IWABOBJECT_SetMe_METHOD;

typedef int IWABOBJECT_;

typedef int WAB_PARAM;

typedef int LPWABOPEN;

typedef int LPWABOPENEX;

typedef int WABIMPORTPARAM;

typedef int WABEXTDISPLAY;

// TODO: this type is limited to platform 'windows5.0'
typedef int IWABExtInit;

typedef enum {
    genderUnspecified = 0,
    genderFemale = 1,
    genderMale = 2,
} Gender;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
