// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (4)
//--------------------------------------------------------------------------------
#define NETWORK_ALIVE_LAN (UINT)1
#define NETWORK_ALIVE_WAN (UINT)2
#define NETWORK_ALIVE_AOL (UINT)4
#define NETWORK_ALIVE_INTERNET (UINT)8

//--------------------------------------------------------------------------------
// Section: Types (8)
//--------------------------------------------------------------------------------
typedef enum {
    CONNECTION_LAN = 0,
    CONNECTION_WAN = 1,
} SENS_CONNECTION_TYPE;

typedef int QOCINFO;

typedef int SENS;

typedef int SENS_QOCINFO;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int ISensNetwork;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int ISensOnNow;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int ISensLogon;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int ISensLogon2;


//--------------------------------------------------------------------------------
// Section: Functions (3)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void IsDestinationReachableA();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void IsDestinationReachableW();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void IsNetworkAlive();

