// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (91)
//--------------------------------------------------------------------------------
#define GPM_USE_PDC (UINT)0
#define GPM_USE_ANYDC (UINT)1
#define GPM_DONOTUSE_W2KDC (UINT)2
#define GPM_DONOT_VALIDATEDC (UINT)1
#define GPM_MIGRATIONTABLE_ONLY (UINT)1
#define GPM_PROCESS_SECURITY (UINT)2
#define RSOP_NO_COMPUTER (UINT)65536
#define RSOP_NO_USER (UINT)131072
#define RSOP_PLANNING_ASSUME_SLOW_LINK (UINT)1
#define RSOP_PLANNING_ASSUME_LOOPBACK_MERGE (UINT)2
#define RSOP_PLANNING_ASSUME_LOOPBACK_REPLACE (UINT)4
#define RSOP_PLANNING_ASSUME_USER_WQLFILTER_TRUE (UINT)8
#define RSOP_PLANNING_ASSUME_COMP_WQLFILTER_TRUE (UINT)16
#define PI_NOUI (UINT)1
#define PI_APPLYPOLICY (UINT)2
#define PT_TEMPORARY (UINT)1
#define PT_ROAMING (UINT)2
#define PT_MANDATORY (UINT)4
#define PT_ROAMING_PREEXISTING (UINT)8
#define RP_FORCE (UINT)1
#define RP_SYNC (UINT)2
#define GPC_BLOCK_POLICY (UINT)1
#define GPO_FLAG_DISABLE (UINT)1
#define GPO_FLAG_FORCE (UINT)2
#define GPO_LIST_FLAG_MACHINE (UINT)1
#define GPO_LIST_FLAG_SITEONLY (UINT)2
#define GPO_LIST_FLAG_NO_WMIFILTERS (UINT)4
#define GPO_LIST_FLAG_NO_SECURITYFILTERS (UINT)8
#define GPO_INFO_FLAG_MACHINE (UINT)1
#define GPO_INFO_FLAG_BACKGROUND (UINT)16
#define GPO_INFO_FLAG_SLOWLINK (UINT)32
#define GPO_INFO_FLAG_VERBOSE (UINT)64
#define GPO_INFO_FLAG_NOCHANGES (UINT)128
#define GPO_INFO_FLAG_LINKTRANSITION (UINT)256
#define GPO_INFO_FLAG_LOGRSOP_TRANSITION (UINT)512
#define GPO_INFO_FLAG_FORCED_REFRESH (UINT)1024
#define GPO_INFO_FLAG_SAFEMODE_BOOT (UINT)2048
#define GPO_INFO_FLAG_ASYNC_FOREGROUND (UINT)4096
#define FLAG_NO_GPO_FILTER (UINT)2147483648
#define FLAG_NO_CSE_INVOKE (UINT)1073741824
#define FLAG_ASSUME_SLOW_LINK (UINT)536870912
#define FLAG_LOOPBACK_MERGE (UINT)268435456
#define FLAG_LOOPBACK_REPLACE (UINT)134217728
#define FLAG_ASSUME_USER_WQLFILTER_TRUE (UINT)67108864
#define FLAG_ASSUME_COMP_WQLFILTER_TRUE (UINT)33554432
#define FLAG_PLANNING_MODE (UINT)16777216
#define FLAG_NO_USER (UINT)1
#define FLAG_NO_COMPUTER (UINT)2
#define FLAG_FORCE_CREATENAMESPACE (UINT)4
#define RSOP_USER_ACCESS_DENIED (UINT)1
#define RSOP_COMPUTER_ACCESS_DENIED (UINT)2
#define RSOP_TEMPNAMESPACE_EXISTS (UINT)4
#define LOCALSTATE_ASSIGNED (UINT)1
#define LOCALSTATE_PUBLISHED (UINT)2
#define LOCALSTATE_UNINSTALL_UNMANAGED (UINT)4
#define LOCALSTATE_POLICYREMOVE_ORPHAN (UINT)8
#define LOCALSTATE_POLICYREMOVE_UNINSTALL (UINT)16
#define LOCALSTATE_ORPHANED (UINT)32
#define LOCALSTATE_UNINSTALLED (UINT)64
#define MANAGED_APPS_USERAPPLICATIONS (UINT)1
#define MANAGED_APPS_FROMCATEGORY (UINT)2
#define MANAGED_APPS_INFOLEVEL_DEFAULT (UINT)65536
#define MANAGED_APPTYPE_WINDOWSINSTALLER (UINT)1
#define MANAGED_APPTYPE_SETUPEXE (UINT)2
#define MANAGED_APPTYPE_UNSUPPORTED (UINT)3
#define CLSID_GPESnapIn GUID { "8fc0b734-a0e1-11d1-a7d3-0000f87571e3" }
#define NODEID_Machine GUID { "8fc0b737-a0e1-11d1-a7d3-0000f87571e3" }
#define NODEID_MachineSWSettings GUID { "8fc0b73a-a0e1-11d1-a7d3-0000f87571e3" }
#define NODEID_User GUID { "8fc0b738-a0e1-11d1-a7d3-0000f87571e3" }
#define NODEID_UserSWSettings GUID { "8fc0b73c-a0e1-11d1-a7d3-0000f87571e3" }
#define CLSID_GroupPolicyObject GUID { "ea502722-a23d-11d1-a7d3-0000f87571e3" }
#define CLSID_RSOPSnapIn GUID { "6dc3804b-7212-458d-adb0-9a07e2ae1fa2" }
#define NODEID_RSOPMachine GUID { "bd4c1a2e-0b7a-4a62-a6b0-c0577539c97e" }
#define NODEID_RSOPMachineSWSettings GUID { "6a76273e-eb8e-45db-94c5-25663a5f2c1a" }
#define NODEID_RSOPUser GUID { "ab87364f-0cec-4cd8-9bf8-898f34628fb8" }
#define NODEID_RSOPUserSWSettings GUID { "e52c5ce3-fd27-4402-84de-d9a5f2858910" }
#define GPO_SECTION_ROOT (UINT)0
#define GPO_SECTION_USER (UINT)1
#define GPO_SECTION_MACHINE (UINT)2
#define GPO_OPEN_LOAD_REGISTRY (UINT)1
#define GPO_OPEN_READ_ONLY (UINT)2
#define GPO_OPTION_DISABLE_USER (UINT)1
#define GPO_OPTION_DISABLE_MACHINE (UINT)2
#define RSOP_INFO_FLAG_DIAGNOSTIC_MODE (UINT)1
#define GPO_BROWSE_DISABLENEW (UINT)1
#define GPO_BROWSE_NOCOMPUTERS (UINT)2
#define GPO_BROWSE_NODSGPOS (UINT)4
#define GPO_BROWSE_OPENBUTTON (UINT)8
#define GPO_BROWSE_INITTOALL (UINT)16
#define GPO_BROWSE_NOUSERGPOS (UINT)32
#define GPO_BROWSE_SENDAPPLYONEDIT (UINT)64

//--------------------------------------------------------------------------------
// Section: Types (109)
//--------------------------------------------------------------------------------
typedef int CriticalPolicySectionHandle;

typedef int GPM;

typedef int GPMDomain;

typedef int GPMSitesContainer;

typedef int GPMBackupDir;

typedef int GPMSOM;

typedef int GPMSearchCriteria;

typedef int GPMPermission;

typedef int GPMSecurityInfo;

typedef int GPMBackup;

typedef int GPMBackupCollection;

typedef int GPMSOMCollection;

typedef int GPMWMIFilter;

typedef int GPMWMIFilterCollection;

typedef int GPMRSOP;

typedef int GPMGPO;

typedef int GPMGPOCollection;

typedef int GPMGPOLink;

typedef int GPMGPOLinksCollection;

typedef int GPMAsyncCancel;

typedef int GPMStatusMsgCollection;

typedef int GPMStatusMessage;

typedef int GPMTrustee;

typedef int GPMClientSideExtension;

typedef int GPMCSECollection;

typedef int GPMConstants;

typedef int GPMResult;

typedef int GPMMapEntryCollection;

typedef int GPMMapEntry;

typedef int GPMMigrationTable;

typedef int GPMBackupDirEx;

typedef int GPMStarterGPOBackupCollection;

typedef int GPMStarterGPOBackup;

typedef int GPMTemplate;

typedef int GPMStarterGPOCollection;

typedef enum {
    rsopUnknown = 0,
    rsopPlanning = 1,
    rsopLogging = 2,
} GPMRSOPMode;

typedef enum {
    permGPOApply = 65536,
    permGPORead = 65792,
    permGPOEdit = 65793,
    permGPOEditSecurityAndDelete = 65794,
    permGPOCustom = 65795,
    permWMIFilterEdit = 131072,
    permWMIFilterFullControl = 131073,
    permWMIFilterCustom = 131074,
    permSOMLink = 1835008,
    permSOMLogging = 1573120,
    permSOMPlanning = 1573376,
    permSOMWMICreate = 1049344,
    permSOMWMIFullControl = 1049345,
    permSOMGPOCreate = 1049600,
    permStarterGPORead = 197888,
    permStarterGPOEdit = 197889,
    permStarterGPOFullControl = 197890,
    permStarterGPOCustom = 197891,
    permSOMStarterGPOCreate = 1049856,
} GPMPermissionType;

typedef enum {
    gpoPermissions = 0,
    gpoEffectivePermissions = 1,
    gpoDisplayName = 2,
    gpoWMIFilter = 3,
    gpoID = 4,
    gpoComputerExtensions = 5,
    gpoUserExtensions = 6,
    somLinks = 7,
    gpoDomain = 8,
    backupMostRecent = 9,
    starterGPOPermissions = 10,
    starterGPOEffectivePermissions = 11,
    starterGPODisplayName = 12,
    starterGPOID = 13,
    starterGPODomain = 14,
} GPMSearchProperty;

typedef enum {
    opEquals = 0,
    opContains = 1,
    opNotContains = 2,
    opNotEquals = 3,
} GPMSearchOperation;

typedef enum {
    repXML = 0,
    repHTML = 1,
    repInfraXML = 2,
    repInfraRefreshXML = 3,
    repClientHealthXML = 4,
    repClientHealthRefreshXML = 5,
} GPMReportType;

typedef enum {
    typeUser = 0,
    typeComputer = 1,
    typeLocalGroup = 2,
    typeGlobalGroup = 3,
    typeUniversalGroup = 4,
    typeUNCPath = 5,
    typeUnknown = 6,
} GPMEntryType;

typedef enum {
    opDestinationSameAsSource = 0,
    opDestinationNone = 1,
    opDestinationByRelativeName = 2,
    opDestinationSet = 3,
} GPMDestinationOption;

typedef enum {
    opReportLegacy = 0,
    opReportComments = 1,
} GPMReportingOptions;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPM;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMDomain;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMBackupDir;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMSitesContainer;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMSearchCriteria;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMTrustee;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMPermission;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMSecurityInfo;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMBackup;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMBackupCollection;

typedef enum {
    somSite = 0,
    somDomain = 1,
    somOU = 2,
} GPMSOMType;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMSOM;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMSOMCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMWMIFilter;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMWMIFilterCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMRSOP;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMGPO;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMGPOCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMGPOLink;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMGPOLinksCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMCSECollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMClientSideExtension;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMAsyncCancel;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMAsyncProgress;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMStatusMsgCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMStatusMessage;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMConstants;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMResult;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMMapEntryCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMMapEntry;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMMigrationTable;

typedef enum {
    typeGPO = 0,
    typeStarterGPO = 1,
} GPMBackupType;

typedef enum {
    typeSystem = 0,
    typeCustom = 1,
} GPMStarterGPOType;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMBackupDirEx;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMStarterGPOBackupCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMStarterGPOBackup;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPM2;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMStarterGPO;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMStarterGPOCollection;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMDomain2;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMConstants2;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPMGPO2;

typedef int IGPMDomain3;

typedef int IGPMGPO3;

typedef enum {
    GPLinkUnknown = 0,
    GPLinkMachine = 1,
    GPLinkSite = 2,
    GPLinkDomain = 3,
    GPLinkOrganizationalUnit = 4,
} GPO_LINK;

typedef int GROUP_POLICY_OBJECTA;

typedef int GROUP_POLICY_OBJECTW;

typedef int PFNSTATUSMESSAGECALLBACK;

typedef int PFNPROCESSGROUPPOLICY;

typedef int PFNPROCESSGROUPPOLICYEX;

typedef int RSOP_TARGET;

typedef int PFNGENERATEGROUPPOLICY;

typedef enum {
    RSOPUnspecified = 0,
    RSOPApplied = 1,
    RSOPIgnored = 2,
    RSOPFailed = 3,
    RSOPSubsettingFailed = 4,
} SETTINGSTATUS;

typedef int POLICYSETTINGSTATUSINFO;

typedef enum {
    APPNAME = 1,
    FILEEXT = 2,
    PROGID = 3,
    COMCLASS = 4,
} INSTALLSPECTYPE;

typedef int INSTALLSPEC;

typedef int INSTALLDATA;

typedef enum {
    ABSENT = 0,
    ASSIGNED = 1,
    PUBLISHED = 2,
} APPSTATE;

typedef int LOCALMANAGEDAPPLICATION;

typedef int MANAGEDAPPLICATION;

typedef enum {
    GPOTypeLocal = 0,
    GPOTypeRemote = 1,
    GPOTypeDS = 2,
    GPOTypeLocalUser = 3,
    GPOTypeLocalGroup = 4,
} GROUP_POLICY_OBJECT_TYPE;

typedef enum {
    GPHintUnknown = 0,
    GPHintMachine = 1,
    GPHintSite = 2,
    GPHintDomain = 3,
    GPHintOrganizationalUnit = 4,
} GROUP_POLICY_HINT_TYPE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGPEInformation;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IGroupPolicyObject;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IRSOPInformation;

typedef int GPOBROWSEINFO;


//--------------------------------------------------------------------------------
// Section: Functions (32)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void RefreshPolicy();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void RefreshPolicyEx();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HANDLE*/void EnterCriticalPolicySection();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void LeaveCriticalPolicySection();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void RegisterGPNotification();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void UnregisterGPNotification();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void GetGPOListA();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void GetGPOListW();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void FreeGPOListA();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void FreeGPOListW();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void GetAppliedGPOListA();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void GetAppliedGPOListW();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void ProcessGroupPolicyCompleted();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void ProcessGroupPolicyCompletedEx();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void RsopAccessCheckByType();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void RsopFileAccessCheck();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void RsopSetPolicySettingStatus();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void RsopResetPolicySettingStatus();

/*u32*/void GenerateGPNotification();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void InstallApplication();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void UninstallApplication();

/*u32*/void CommandLineFromMsiDescriptor();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void GetManagedApplications();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void GetLocalManagedApplications();

/*void*/void GetLocalManagedApplicationData();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void GetManagedApplicationCategories();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void CreateGPOLink();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void DeleteGPOLink();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void DeleteAllGPOLinks();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void BrowseForGPO();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void ImportRSoPData();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void ExportRSoPData();

