// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (17)
//--------------------------------------------------------------------------------
#define OBJ_HANDLE_TAGBITS (INT)3
#define RTL_BALANCED_NODE_RESERVED_PARENT_MASK (UINT)3
#define OBJ_INHERIT (INT)2
#define OBJ_PERMANENT (INT)16
#define OBJ_EXCLUSIVE (INT)32
#define OBJ_CASE_INSENSITIVE (INT)64
#define OBJ_OPENIF (INT)128
#define OBJ_OPENLINK (INT)256
#define OBJ_KERNEL_HANDLE (INT)512
#define OBJ_FORCE_ACCESS_CHECK (INT)1024
#define OBJ_IGNORE_IMPERSONATED_DEVICEMAP (INT)2048
#define OBJ_DONT_REPARSE (INT)4096
#define OBJ_VALID_ATTRIBUTES (INT)8178
#define NULL64 (UINT)0
#define MAXUCHAR (UINT)255
#define MAXUSHORT (UINT)65535
#define MAXULONG (UINT)4294967295

//--------------------------------------------------------------------------------
// Section: Types (31)
//--------------------------------------------------------------------------------
typedef enum {
    ExceptionContinueExecution = 0,
    ExceptionContinueSearch = 1,
    ExceptionNestedException = 2,
    ExceptionCollidedUnwind = 3,
} EXCEPTION_DISPOSITION;

typedef int SLIST_HEADER;

typedef int FLOATING_SAVE_AREA;

typedef enum {
    UNSPECIFIED_COMPARTMENT_ID = 0,
    DEFAULT_COMPARTMENT_ID = 1,
} COMPARTMENT_ID;

typedef int SLIST_ENTRY;

typedef int SLIST_HEADER;

typedef int QUAD;

typedef int PROCESSOR_NUMBER;

typedef int GROUP_AFFINITY;

typedef enum {
    NotificationEvent = 0,
    SynchronizationEvent = 1,
} EVENT_TYPE;

typedef enum {
    NotificationTimer = 0,
    SynchronizationTimer = 1,
} TIMER_TYPE;

typedef enum {
    WaitAll = 0,
    WaitAny = 1,
    WaitNotification = 2,
    WaitDequeue = 3,
} WAIT_TYPE;

typedef int STRING;

typedef int CSTRING;

typedef int UNICODE_STRING;

typedef int LIST_ENTRY;

typedef int RTL_BALANCED_NODE;

typedef int LIST_ENTRY32;

typedef int LIST_ENTRY64;

typedef int SINGLE_LIST_ENTRY32;

typedef int WNF_STATE_NAME;

typedef int STRING32;

typedef int STRING64;

typedef int OBJECT_ATTRIBUTES64;

typedef int OBJECT_ATTRIBUTES32;

typedef int OBJECTID;

typedef int EXCEPTION_ROUTINE;

typedef enum {
    NtProductWinNt = 1,
    NtProductLanManNt = 2,
    NtProductServer = 3,
} NT_PRODUCT_TYPE;

typedef enum {
    SmallBusiness = 0,
    Enterprise = 1,
    BackOffice = 2,
    CommunicationServer = 3,
    TerminalServer = 4,
    SmallBusinessRestricted = 5,
    EmbeddedNT = 6,
    DataCenter = 7,
    SingleUserTS = 8,
    Personal = 9,
    Blade = 10,
    EmbeddedRestricted = 11,
    SecurityAppliance = 12,
    StorageServer = 13,
    ComputeServer = 14,
    WHServer = 15,
    PhoneNT = 16,
    MultiUserTS = 17,
    MaxSuiteType = 18,
} SUITE_TYPE;

typedef int FLOATING_SAVE_AREA;

typedef int SLIST_HEADER;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
