// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Types (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Functions (4)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.0'
/*HANDLE*/void CreateMailslotA();

// TODO: this type is limited to platform 'windows5.0'
/*HANDLE*/void CreateMailslotW();

// TODO: this type is limited to platform 'windows5.0'
/*BOOL*/void GetMailslotInfo();

// TODO: this type is limited to platform 'windows5.0'
/*BOOL*/void SetMailslotInfo();

