// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (1)
//--------------------------------------------------------------------------------
#define PSAPI_VERSION (UINT)2

//--------------------------------------------------------------------------------
// Section: Types (14)
//--------------------------------------------------------------------------------
typedef enum {
    LIST_MODULES_ALL = 3,
    LIST_MODULES_DEFAULT = 0,
    LIST_MODULES_32BIT = 1,
    LIST_MODULES_64BIT = 2,
} ENUM_PROCESS_MODULES_EX_FLAGS;

typedef int MODULEINFO;

typedef int PSAPI_WORKING_SET_BLOCK;

typedef int PSAPI_WORKING_SET_INFORMATION;

typedef int PSAPI_WORKING_SET_EX_BLOCK;

typedef int PSAPI_WORKING_SET_EX_INFORMATION;

typedef int PSAPI_WS_WATCH_INFORMATION;

typedef int PSAPI_WS_WATCH_INFORMATION_EX;

typedef int PROCESS_MEMORY_COUNTERS;

typedef int PROCESS_MEMORY_COUNTERS_EX;

typedef int PERFORMANCE_INFORMATION;

typedef int ENUM_PAGE_FILE_INFORMATION;

typedef int PENUM_PAGE_FILE_CALLBACKW;

typedef int PENUM_PAGE_FILE_CALLBACKA;


//--------------------------------------------------------------------------------
// Section: Functions (27)
//--------------------------------------------------------------------------------
/*BOOL*/void K32EnumProcesses();

/*BOOL*/void K32EnumProcessModules();

/*BOOL*/void K32EnumProcessModulesEx();

/*u32*/void K32GetModuleBaseNameA();

/*u32*/void K32GetModuleBaseNameW();

/*u32*/void K32GetModuleFileNameExA();

/*u32*/void K32GetModuleFileNameExW();

/*BOOL*/void K32GetModuleInformation();

/*BOOL*/void K32EmptyWorkingSet();

/*BOOL*/void K32QueryWorkingSet();

/*BOOL*/void K32QueryWorkingSetEx();

/*BOOL*/void K32InitializeProcessForWsWatch();

/*BOOL*/void K32GetWsChanges();

/*BOOL*/void K32GetWsChangesEx();

/*u32*/void K32GetMappedFileNameW();

/*u32*/void K32GetMappedFileNameA();

/*BOOL*/void K32EnumDeviceDrivers();

/*u32*/void K32GetDeviceDriverBaseNameA();

/*u32*/void K32GetDeviceDriverBaseNameW();

/*u32*/void K32GetDeviceDriverFileNameA();

/*u32*/void K32GetDeviceDriverFileNameW();

/*BOOL*/void K32GetProcessMemoryInfo();

/*BOOL*/void K32GetPerformanceInfo();

/*BOOL*/void K32EnumPageFilesW();

/*BOOL*/void K32EnumPageFilesA();

/*u32*/void K32GetProcessImageFileNameA();

/*u32*/void K32GetProcessImageFileNameW();

