// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (1)
//--------------------------------------------------------------------------------
#define PKEY_PIDSTR_MAX (UINT)10

//--------------------------------------------------------------------------------
// Section: Types (59)
//--------------------------------------------------------------------------------
typedef int SERIALIZEDPROPSTORAGE;

typedef int PROPERTYKEY;

typedef int InMemoryPropertyStore;

typedef int InMemoryPropertyStoreMarshalByValue;

typedef int PropertySystem;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IInitializeWithFile;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IInitializeWithStream;

typedef int IPropertyStore;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int INamedPropertyStore;

typedef enum {
    GPS_DEFAULT = 0,
    GPS_HANDLERPROPERTIESONLY = 1,
    GPS_READWRITE = 2,
    GPS_TEMPORARY = 4,
    GPS_FASTPROPERTIESONLY = 8,
    GPS_OPENSLOWITEM = 16,
    GPS_DELAYCREATION = 32,
    GPS_BESTEFFORT = 64,
    GPS_NO_OPLOCK = 128,
    GPS_PREFERQUERYPROPERTIES = 256,
    GPS_EXTRINSICPROPERTIES = 512,
    GPS_EXTRINSICPROPERTIESONLY = 1024,
    GPS_VOLATILEPROPERTIES = 2048,
    GPS_VOLATILEPROPERTIESONLY = 4096,
    GPS_MASK_VALID = 8191,
} GETPROPERTYSTOREFLAGS;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IObjectWithPropertyKey;

typedef enum {
    PKA_SET = 0,
    PKA_APPEND = 1,
    PKA_DELETE = 2,
} PKA_FLAGS;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyChange;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyChangeArray;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyStoreCapabilities;

typedef enum {
    PSC_NORMAL = 0,
    PSC_NOTINSOURCE = 1,
    PSC_DIRTY = 2,
    PSC_READONLY = 3,
} PSC_STATE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyStoreCache;

typedef enum {
    PET_DISCRETEVALUE = 0,
    PET_RANGEDVALUE = 1,
    PET_DEFAULTVALUE = 2,
    PET_ENDRANGE = 3,
} PROPENUMTYPE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyEnumType;

// TODO: this type is limited to platform 'windows6.1'
typedef int IPropertyEnumType2;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyEnumTypeList;

typedef enum {
    PDTF_DEFAULT = 0,
    PDTF_MULTIPLEVALUES = 1,
    PDTF_ISINNATE = 2,
    PDTF_ISGROUP = 4,
    PDTF_CANGROUPBY = 8,
    PDTF_CANSTACKBY = 16,
    PDTF_ISTREEPROPERTY = 32,
    PDTF_INCLUDEINFULLTEXTQUERY = 64,
    PDTF_ISVIEWABLE = 128,
    PDTF_ISQUERYABLE = 256,
    PDTF_CANBEPURGED = 512,
    PDTF_SEARCHRAWVALUE = 1024,
    PDTF_DONTCOERCEEMPTYSTRINGS = 2048,
    PDTF_ALWAYSINSUPPLEMENTALSTORE = 4096,
    PDTF_ISSYSTEMPROPERTY = -2147483648,
    PDTF_MASK_ALL = -2147475457,
} PROPDESC_TYPE_FLAGS;

typedef enum {
    PDVF_DEFAULT = 0,
    PDVF_CENTERALIGN = 1,
    PDVF_RIGHTALIGN = 2,
    PDVF_BEGINNEWGROUP = 4,
    PDVF_FILLAREA = 8,
    PDVF_SORTDESCENDING = 16,
    PDVF_SHOWONLYIFPRESENT = 32,
    PDVF_SHOWBYDEFAULT = 64,
    PDVF_SHOWINPRIMARYLIST = 128,
    PDVF_SHOWINSECONDARYLIST = 256,
    PDVF_HIDELABEL = 512,
    PDVF_HIDDEN = 2048,
    PDVF_CANWRAP = 4096,
    PDVF_MASK_ALL = 7167,
} PROPDESC_VIEW_FLAGS;

typedef enum {
    PDDT_STRING = 0,
    PDDT_NUMBER = 1,
    PDDT_BOOLEAN = 2,
    PDDT_DATETIME = 3,
    PDDT_ENUMERATED = 4,
} PROPDESC_DISPLAYTYPE;

typedef enum {
    PDGR_DISCRETE = 0,
    PDGR_ALPHANUMERIC = 1,
    PDGR_SIZE = 2,
    PDGR_DYNAMIC = 3,
    PDGR_DATE = 4,
    PDGR_PERCENT = 5,
    PDGR_ENUMERATED = 6,
} PROPDESC_GROUPING_RANGE;

typedef enum {
    PDFF_DEFAULT = 0,
    PDFF_PREFIXNAME = 1,
    PDFF_FILENAME = 2,
    PDFF_ALWAYSKB = 4,
    PDFF_RESERVED_RIGHTTOLEFT = 8,
    PDFF_SHORTTIME = 16,
    PDFF_LONGTIME = 32,
    PDFF_HIDETIME = 64,
    PDFF_SHORTDATE = 128,
    PDFF_LONGDATE = 256,
    PDFF_HIDEDATE = 512,
    PDFF_RELATIVEDATE = 1024,
    PDFF_USEEDITINVITATION = 2048,
    PDFF_READONLY = 4096,
    PDFF_NOAUTOREADINGORDER = 8192,
} PROPDESC_FORMAT_FLAGS;

typedef enum {
    PDSD_GENERAL = 0,
    PDSD_A_Z = 1,
    PDSD_LOWEST_HIGHEST = 2,
    PDSD_SMALLEST_BIGGEST = 3,
    PDSD_OLDEST_NEWEST = 4,
} PROPDESC_SORTDESCRIPTION;

typedef enum {
    PDRDT_GENERAL = 0,
    PDRDT_DATE = 1,
    PDRDT_SIZE = 2,
    PDRDT_COUNT = 3,
    PDRDT_REVISION = 4,
    PDRDT_LENGTH = 5,
    PDRDT_DURATION = 6,
    PDRDT_SPEED = 7,
    PDRDT_RATE = 8,
    PDRDT_RATING = 9,
    PDRDT_PRIORITY = 10,
} PROPDESC_RELATIVEDESCRIPTION_TYPE;

typedef enum {
    PDAT_DEFAULT = 0,
    PDAT_FIRST = 1,
    PDAT_SUM = 2,
    PDAT_AVERAGE = 3,
    PDAT_DATERANGE = 4,
    PDAT_UNION = 5,
    PDAT_MAX = 6,
    PDAT_MIN = 7,
} PROPDESC_AGGREGATION_TYPE;

typedef enum {
    PDCOT_NONE = 0,
    PDCOT_STRING = 1,
    PDCOT_SIZE = 2,
    PDCOT_DATETIME = 3,
    PDCOT_BOOLEAN = 4,
    PDCOT_NUMBER = 5,
} PROPDESC_CONDITION_TYPE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyDescription;

// TODO: this type is limited to platform 'windows6.1'
typedef int IPropertyDescription2;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyDescriptionAliasInfo;

typedef enum {
    PDSIF_DEFAULT = 0,
    PDSIF_ININVERTEDINDEX = 1,
    PDSIF_ISCOLUMN = 2,
    PDSIF_ISCOLUMNSPARSE = 4,
    PDSIF_ALWAYSINCLUDE = 8,
    PDSIF_USEFORTYPEAHEAD = 16,
} PROPDESC_SEARCHINFO_FLAGS;

typedef enum {
    PDCIT_NONE = 0,
    PDCIT_ONDISK = 1,
    PDCIT_INMEMORY = 2,
    PDCIT_ONDEMAND = 3,
    PDCIT_ONDISKALL = 4,
    PDCIT_ONDISKVECTOR = 5,
} PROPDESC_COLUMNINDEX_TYPE;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyDescriptionSearchInfo;

// TODO: this type is limited to platform 'windows6.1'
typedef int IPropertyDescriptionRelatedPropertyInfo;

typedef enum {
    PDEF_ALL = 0,
    PDEF_SYSTEM = 1,
    PDEF_NONSYSTEM = 2,
    PDEF_VIEWABLE = 3,
    PDEF_QUERYABLE = 4,
    PDEF_INFULLTEXTQUERY = 5,
    PDEF_COLUMN = 6,
} PROPDESC_ENUMFILTER;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IPropertySystem;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyDescriptionList;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPropertyStoreFactory;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IDelayedPropertyStoreFactory;

typedef enum {
    FPSPS_DEFAULT = 0,
    FPSPS_READONLY = 1,
    FPSPS_TREAT_NEW_VALUES_AS_DIRTY = 2,
} _PERSIST_SPROPSTORE_FLAGS;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int IPersistSerializedPropStorage;

// TODO: this type is limited to platform 'windows6.1'
typedef int IPersistSerializedPropStorage2;

typedef int IPropertySystemChangeNotify;

// TODO: this type is limited to platform 'windows6.0.6000'
typedef int ICreateObject;

typedef enum {
    PSTF_UTC = 0,
    PSTF_LOCAL = 1,
} PSTIME_FLAGS;

typedef enum {
    PVCU_DEFAULT = 0,
    PVCU_SECOND = 1,
    PVCU_MINUTE = 2,
    PVCU_HOUR = 3,
    PVCU_DAY = 4,
    PVCU_MONTH = 5,
    PVCU_YEAR = 6,
} PROPVAR_COMPARE_UNIT;

typedef enum {
    PVCF_DEFAULT = 0,
    PVCF_TREATEMPTYASGREATERTHAN = 1,
    PVCF_USESTRCMP = 2,
    PVCF_USESTRCMPC = 4,
    PVCF_USESTRCMPI = 8,
    PVCF_USESTRCMPIC = 16,
    PVCF_DIGITSASNUMBERS_CASESENSITIVE = 32,
} PROPVAR_COMPARE_FLAGS;

typedef enum {
    PVCHF_DEFAULT = 0,
    PVCHF_NOVALUEPROP = 1,
    PVCHF_ALPHABOOL = 2,
    PVCHF_NOUSEROVERRIDE = 4,
    PVCHF_LOCALBOOL = 8,
    PVCHF_NOHEXSTRING = 16,
} PROPVAR_CHANGE_FLAGS;

typedef enum {
    DPF_NONE = 0,
    DPF_MARQUEE = 1,
    DPF_MARQUEE_COMPLETE = 2,
    DPF_ERROR = 4,
    DPF_WARNING = 8,
    DPF_STOPPED = 16,
} DRAWPROGRESSFLAGS;

typedef enum {
    STS_NONE = 0,
    STS_NEEDSUPLOAD = 1,
    STS_NEEDSDOWNLOAD = 2,
    STS_TRANSFERRING = 4,
    STS_PAUSED = 8,
    STS_HASERROR = 16,
    STS_FETCHING_METADATA = 32,
    STS_USER_REQUESTED_REFRESH = 64,
    STS_HASWARNING = 128,
    STS_EXCLUDED = 256,
    STS_INCOMPLETE = 512,
    STS_PLACEHOLDER_IFEMPTY = 1024,
} SYNC_TRANSFER_STATUS;

typedef enum {
    PS_NONE = 0,
    PS_MARKED_FOR_OFFLINE_AVAILABILITY = 1,
    PS_FULL_PRIMARY_STREAM_AVAILABLE = 2,
    PS_CREATE_FILE_ACCESSIBLE = 4,
    PS_CLOUDFILE_PLACEHOLDER = 8,
    PS_DEFAULT = 7,
    PS_ALL = 15,
} PLACEHOLDER_STATES;

typedef enum {
    PUIF_DEFAULT = 0,
    PUIF_RIGHTALIGN = 1,
    PUIF_NOLABELININFOTIP = 2,
} _PROPERTYUI_FLAGS;

// TODO: this type is limited to platform 'windows5.0'
typedef int IPropertyUI;

typedef enum {
    PDOPS_RUNNING = 1,
    PDOPS_PAUSED = 2,
    PDOPS_CANCELLED = 3,
    PDOPS_STOPPED = 4,
    PDOPS_ERRORS = 5,
} PDOPSTATUS;

typedef enum {
    SESF_NONE = 0,
    SESF_SERVICE_QUOTA_NEARING_LIMIT = 1,
    SESF_SERVICE_QUOTA_EXCEEDED_LIMIT = 2,
    SESF_AUTHENTICATION_ERROR = 4,
    SESF_PAUSED_DUE_TO_METERED_NETWORK = 8,
    SESF_PAUSED_DUE_TO_DISK_SPACE_FULL = 16,
    SESF_PAUSED_DUE_TO_CLIENT_POLICY = 32,
    SESF_PAUSED_DUE_TO_SERVICE_POLICY = 64,
    SESF_SERVICE_UNAVAILABLE = 128,
    SESF_PAUSED_DUE_TO_USER_REQUEST = 256,
    SESF_ALL_FLAGS = 511,
} SYNC_ENGINE_STATE_FLAGS;

typedef int PROPPRG;


//--------------------------------------------------------------------------------
// Section: Functions (227)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void PropVariantToWinRTPropertyValue();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void WinRTPropertyValueToPropVariant();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void PSFormatForDisplay();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void PSFormatForDisplayAlloc();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void PSFormatPropertyValue();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSGetImageReferenceForValue();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSStringFromPropertyKey();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSPropertyKeyFromString();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreateMemoryPropertyStore();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreateDelayedMultiplexPropertyStore();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreateMultiplexPropertyStore();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreatePropertyChangeArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreateSimplePropertyChange();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertyDescription();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertyDescriptionByName();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSLookupPropertyHandlerCLSID();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetItemPropertyHandler();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetItemPropertyHandlerWithCreateObject();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertyValue();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSSetPropertyValue();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSRegisterPropertySchema();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSUnregisterPropertySchema();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSRefreshPropertySchema();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSEnumeratePropertyDescriptions();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertyKeyFromName();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetNameFromPropertyKey();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCoerceToCanonicalValue();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertyDescriptionListFromString();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreatePropertyStoreFromPropertySetStorage();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreatePropertyStoreFromObject();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSCreateAdapterFromPropertyStore();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertySystem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetPropertyFromPropertyStorage();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PSGetNamedPropertyFromPropertyStorage();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadType();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadStr();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadStrAlloc();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadBSTR();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteStr();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteBSTR();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadInt();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteInt();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadSHORT();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteSHORT();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadLONG();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteLONG();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadDWORD();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteDWORD();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadBOOL();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteBOOL();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadPOINTL();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WritePOINTL();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadPOINTS();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WritePOINTS();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadRECTL();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteRECTL();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadStream();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteStream();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_Delete();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadULONGLONG();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteULONGLONG();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadUnknown();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteUnknown();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadGUID();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WriteGUID();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_ReadPropertyKey();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void PSPropertyBag_WritePropertyKey();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromResource();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromBuffer();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromCLSID();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromGUIDAsString();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromFileTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromPropVariantVectorElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantVectorFromPropVariant();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromStrRet();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromBooleanVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromInt16Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromUInt16Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromInt32Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromUInt32Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromInt64Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromUInt64Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromDoubleVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromFileTimeVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromStringVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitPropVariantFromStringAsVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void PropVariantToBooleanWithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i16*/void PropVariantToInt16WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u16*/void PropVariantToUInt16WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i32*/void PropVariantToInt32WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u32*/void PropVariantToUInt32WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i64*/void PropVariantToInt64WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u64*/void PropVariantToUInt64WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*f64*/void PropVariantToDoubleWithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*PWSTR*/void PropVariantToStringWithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToBoolean();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt16();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt16();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt32();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt32();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt64();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt64();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToDouble();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToBuffer();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToString();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToGUID();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToStringAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToBSTR();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToStrRet();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToFileTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u32*/void PropVariantGetElementCount();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToBooleanVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt16Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt16Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt32Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt32Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt64Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt64Vector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToDoubleVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToFileTimeVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToStringVector();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToBooleanVectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt16VectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt16VectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt32VectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt32VectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToInt64VectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToUInt64VectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToDoubleVectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToFileTimeVectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantToStringVectorAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetBooleanElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetInt16Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetUInt16Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetInt32Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetUInt32Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetInt64Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetUInt64Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetDoubleElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetFileTimeElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantGetStringElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*void*/void ClearPropVariantArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i32*/void PropVariantCompareEx();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PropVariantChangeType();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void PropVariantToVariant();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void VariantToPropVariant();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromResource();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromBuffer();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromGUIDAsString();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromFileTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromFileTimeArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromStrRet();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromVariantArrayElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromBooleanArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromInt16Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromUInt16Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromInt32Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromUInt32Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromInt64Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromUInt64Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromDoubleArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void InitVariantFromStringArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void VariantToBooleanWithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i16*/void VariantToInt16WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u16*/void VariantToUInt16WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i32*/void VariantToInt32WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u32*/void VariantToUInt32WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i64*/void VariantToInt64WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u64*/void VariantToUInt64WithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*f64*/void VariantToDoubleWithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*PWSTR*/void VariantToStringWithDefault();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToBoolean();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt16();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt16();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt32();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt32();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt64();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt64();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToDouble();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToBuffer();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToGUID();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToString();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToStringAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToDosDateTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToStrRet();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToFileTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*u32*/void VariantGetElementCount();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToBooleanArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt16Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt16Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt32Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt32Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt64Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt64Array();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToDoubleArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToStringArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToBooleanArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt16ArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt16ArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt32ArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt32ArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToInt64ArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToUInt64ArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToDoubleArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantToStringArrayAlloc();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetBooleanElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetInt16Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetUInt16Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetInt32Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetUInt32Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetInt64Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetUInt64Elem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetDoubleElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void VariantGetStringElem();

// TODO: this type is limited to platform 'windows5.1.2600'
/*void*/void ClearVariantArray();

// TODO: this type is limited to platform 'windows5.1.2600'
/*i32*/void VariantCompare();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void SHGetPropertyStoreFromIDList();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void SHGetPropertyStoreFromParsingName();

// TODO: this type is limited to platform 'windows6.0.6000'
/*HRESULT*/void SHAddDefaultPropertiesByExt();

// TODO: this type is limited to platform 'windows5.0'
/*HANDLE*/void PifMgr_OpenProperties();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void PifMgr_GetProperties();

// TODO: this type is limited to platform 'windows5.0'
/*i32*/void PifMgr_SetProperties();

// TODO: this type is limited to platform 'windows5.0'
/*HANDLE*/void PifMgr_CloseProperties();

// TODO: this type is limited to platform 'windows5.0'
/*HRESULT*/void SHPropStgCreate();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void SHPropStgReadMultiple();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void SHPropStgWriteMultiple();

// TODO: this type is limited to platform 'windows6.1'
/*HRESULT*/void SHGetPropertyStoreForWindow();

