// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (4)
//--------------------------------------------------------------------------------
#define TSF_Hardware (UINT)1
#define TSF_Authenticated (UINT)2
#define TSF_IPv6 (UINT)4
#define TSF_SignatureAuthenticated (UINT)8

//--------------------------------------------------------------------------------
// Section: Types (2)
//--------------------------------------------------------------------------------
typedef int TIME_ZONE_INFORMATION;

typedef int DYNAMIC_TIME_ZONE_INFORMATION;


//--------------------------------------------------------------------------------
// Section: Functions (15)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.0'
/*BOOL*/void SystemTimeToTzSpecificLocalTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void TzSpecificLocalTimeToSystemTime();

// TODO: this type is limited to platform 'windows5.1.2600'
/*BOOL*/void FileTimeToSystemTime();

// TODO: this type is limited to platform 'windows5.0'
/*BOOL*/void SystemTimeToFileTime();

// TODO: this type is limited to platform 'windows5.0'
/*u32*/void GetTimeZoneInformation();

// TODO: this type is limited to platform 'windows5.0'
/*BOOL*/void SetTimeZoneInformation();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void SetDynamicTimeZoneInformation();

// TODO: this type is limited to platform 'windows6.0.6000'
/*u32*/void GetDynamicTimeZoneInformation();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void GetTimeZoneInformationForYear();

// TODO: this type is limited to platform 'windows8.0'
/*u32*/void EnumDynamicTimeZoneInformation();

// TODO: this type is limited to platform 'windows8.0'
/*u32*/void GetDynamicTimeZoneInformationEffectiveYears();

// TODO: this type is limited to platform 'windows6.1'
/*BOOL*/void SystemTimeToTzSpecificLocalTimeEx();

// TODO: this type is limited to platform 'windows6.1'
/*BOOL*/void TzSpecificLocalTimeToSystemTimeEx();

/*BOOL*/void LocalFileTimeToLocalSystemTime();

/*BOOL*/void LocalSystemTimeToLocalFileTime();

