// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (7)
//--------------------------------------------------------------------------------
#define PRINTTICKET_ISTREAM_APIS (UINT)1
#define S_PT_NO_CONFLICT (UINT)262145
#define S_PT_CONFLICT_RESOLVED (UINT)262146
#define E_PRINTTICKET_FORMAT (UINT)2147745795
#define E_PRINTCAPABILITIES_FORMAT (UINT)2147745796
#define E_DELTA_PRINTTICKET_FORMAT (UINT)2147745797
#define E_PRINTDEVICECAPABILITIES_FORMAT (UINT)2147745798

//--------------------------------------------------------------------------------
// Section: Types (2)
//--------------------------------------------------------------------------------
typedef enum {
    kUserDefaultDevmode = 0,
    kPrinterDefaultDevmode = 1,
} EDefaultDevmodeType;

typedef enum {
    kPTPageScope = 0,
    kPTDocumentScope = 1,
    kPTJobScope = 2,
} EPrintTicketScope;


//--------------------------------------------------------------------------------
// Section: Functions (11)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTQuerySchemaVersionSupport();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTOpenProvider();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTOpenProviderEx();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTCloseProvider();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTReleaseMemory();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTGetPrintCapabilities();

// TODO: this type is limited to platform 'windows10.0.15063'
/*HRESULT*/void PTGetPrintDeviceCapabilities();

// TODO: this type is limited to platform 'windows10.0.15063'
/*HRESULT*/void PTGetPrintDeviceResources();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTMergeAndValidatePrintTicket();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTConvertPrintTicketToDevMode();

// TODO: this type is limited to platform 'windows5.1.2600'
/*HRESULT*/void PTConvertDevModeToPrintTicket();

