// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (4)
//--------------------------------------------------------------------------------
#define UI_ANIMATION_SECONDS_EVENTUALLY (INT)-1
#define UI_ANIMATION_REPEAT_INDEFINITELY (INT)-1
#define UI_ANIMATION_REPEAT_INDEFINITELY_CONCLUDE_AT_START (INT)-2
#define UI_ANIMATION_SECONDS_INFINITE (INT)-1

//--------------------------------------------------------------------------------
// Section: Types (51)
//--------------------------------------------------------------------------------
typedef int UI_ANIMATION_KEYFRAME;

typedef int UIAnimationManager;

typedef int UIAnimationManager2;

typedef int UIAnimationTransitionLibrary;

typedef int UIAnimationTransitionLibrary2;

typedef int UIAnimationTransitionFactory;

typedef int UIAnimationTransitionFactory2;

typedef int UIAnimationTimer;

typedef enum {
    UI_ANIMATION_UPDATE_NO_CHANGE = 0,
    UI_ANIMATION_UPDATE_VARIABLES_CHANGED = 1,
} UI_ANIMATION_UPDATE_RESULT;

typedef enum {
    UI_ANIMATION_MANAGER_IDLE = 0,
    UI_ANIMATION_MANAGER_BUSY = 1,
} UI_ANIMATION_MANAGER_STATUS;

typedef enum {
    UI_ANIMATION_MODE_DISABLED = 0,
    UI_ANIMATION_MODE_SYSTEM_DEFAULT = 1,
    UI_ANIMATION_MODE_ENABLED = 2,
} UI_ANIMATION_MODE;

typedef enum {
    UI_ANIMATION_REPEAT_MODE_NORMAL = 0,
    UI_ANIMATION_REPEAT_MODE_ALTERNATE = 1,
} UI_ANIMATION_REPEAT_MODE;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationManager;

typedef enum {
    UI_ANIMATION_ROUNDING_NEAREST = 0,
    UI_ANIMATION_ROUNDING_FLOOR = 1,
    UI_ANIMATION_ROUNDING_CEILING = 2,
} UI_ANIMATION_ROUNDING_MODE;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationVariable;

typedef enum {
    UI_ANIMATION_STORYBOARD_BUILDING = 0,
    UI_ANIMATION_STORYBOARD_SCHEDULED = 1,
    UI_ANIMATION_STORYBOARD_CANCELLED = 2,
    UI_ANIMATION_STORYBOARD_PLAYING = 3,
    UI_ANIMATION_STORYBOARD_TRUNCATED = 4,
    UI_ANIMATION_STORYBOARD_FINISHED = 5,
    UI_ANIMATION_STORYBOARD_READY = 6,
    UI_ANIMATION_STORYBOARD_INSUFFICIENT_PRIORITY = 7,
} UI_ANIMATION_STORYBOARD_STATUS;

typedef enum {
    UI_ANIMATION_SCHEDULING_UNEXPECTED_FAILURE = 0,
    UI_ANIMATION_SCHEDULING_INSUFFICIENT_PRIORITY = 1,
    UI_ANIMATION_SCHEDULING_ALREADY_SCHEDULED = 2,
    UI_ANIMATION_SCHEDULING_SUCCEEDED = 3,
    UI_ANIMATION_SCHEDULING_DEFERRED = 4,
} UI_ANIMATION_SCHEDULING_RESULT;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationStoryboard;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTransition;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationManagerEventHandler;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationVariableChangeHandler;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationVariableIntegerChangeHandler;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationStoryboardEventHandler;

typedef enum {
    UI_ANIMATION_PRIORITY_EFFECT_FAILURE = 0,
    UI_ANIMATION_PRIORITY_EFFECT_DELAY = 1,
} UI_ANIMATION_PRIORITY_EFFECT;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationPriorityComparison;

typedef enum {
    UI_ANIMATION_SLOPE_INCREASING = 0,
    UI_ANIMATION_SLOPE_DECREASING = 1,
} UI_ANIMATION_SLOPE;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTransitionLibrary;

typedef enum {
    UI_ANIMATION_DEPENDENCY_NONE = 0,
    UI_ANIMATION_DEPENDENCY_INTERMEDIATE_VALUES = 1,
    UI_ANIMATION_DEPENDENCY_FINAL_VALUE = 2,
    UI_ANIMATION_DEPENDENCY_FINAL_VELOCITY = 4,
    UI_ANIMATION_DEPENDENCY_DURATION = 8,
} UI_ANIMATION_DEPENDENCIES;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationInterpolator;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTransitionFactory;

typedef enum {
    UI_ANIMATION_IDLE_BEHAVIOR_CONTINUE = 0,
    UI_ANIMATION_IDLE_BEHAVIOR_DISABLE = 1,
} UI_ANIMATION_IDLE_BEHAVIOR;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTimer;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTimerUpdateHandler;

typedef enum {
    UI_ANIMATION_TIMER_CLIENT_IDLE = 0,
    UI_ANIMATION_TIMER_CLIENT_BUSY = 1,
} UI_ANIMATION_TIMER_CLIENT_STATUS;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTimerClientEventHandler;

// TODO: this type is limited to platform 'windows6.1'
typedef int IUIAnimationTimerEventHandler;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationManager2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationVariable2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationTransition2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationManagerEventHandler2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationVariableChangeHandler2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationVariableIntegerChangeHandler2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationVariableCurveChangeHandler2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationStoryboardEventHandler2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationLoopIterationChangeHandler2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationPriorityComparison2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationTransitionLibrary2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationPrimitiveInterpolation;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationInterpolator2;

// TODO: this type is limited to platform 'windows8.0'
typedef int IUIAnimationTransitionFactory2;

typedef int IUIAnimationStoryboard2;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
