// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Types (25)
//--------------------------------------------------------------------------------
typedef int HINTERACTIONCONTEXT;

typedef enum {
    INTERACTION_ID_NONE = 0,
    INTERACTION_ID_MANIPULATION = 1,
    INTERACTION_ID_TAP = 2,
    INTERACTION_ID_SECONDARY_TAP = 3,
    INTERACTION_ID_HOLD = 4,
    INTERACTION_ID_DRAG = 5,
    INTERACTION_ID_CROSS_SLIDE = 6,
    INTERACTION_ID_MAX = -1,
} INTERACTION_ID;

typedef enum {
    INTERACTION_FLAG_NONE = 0,
    INTERACTION_FLAG_BEGIN = 1,
    INTERACTION_FLAG_END = 2,
    INTERACTION_FLAG_CANCEL = 4,
    INTERACTION_FLAG_INERTIA = 8,
    INTERACTION_FLAG_MAX = 4294967295,
} INTERACTION_FLAGS;

typedef enum {
    INTERACTION_CONFIGURATION_FLAG_NONE = 0,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION = 1,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_X = 2,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_Y = 4,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_ROTATION = 8,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_SCALING = 16,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_INERTIA = 32,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_ROTATION_INERTIA = 64,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_SCALING_INERTIA = 128,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_RAILS_X = 256,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_RAILS_Y = 512,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_EXACT = 1024,
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_MULTIPLE_FINGER_PANNING = 2048,
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE = 1,
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_HORIZONTAL = 2,
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_SELECT = 4,
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_SPEED_BUMP = 8,
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_REARRANGE = 16,
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_EXACT = 32,
    INTERACTION_CONFIGURATION_FLAG_TAP = 1,
    INTERACTION_CONFIGURATION_FLAG_TAP_DOUBLE = 2,
    INTERACTION_CONFIGURATION_FLAG_TAP_MULTIPLE_FINGER = 4,
    INTERACTION_CONFIGURATION_FLAG_SECONDARY_TAP = 1,
    INTERACTION_CONFIGURATION_FLAG_HOLD = 1,
    INTERACTION_CONFIGURATION_FLAG_HOLD_MOUSE = 2,
    INTERACTION_CONFIGURATION_FLAG_HOLD_MULTIPLE_FINGER = 4,
    INTERACTION_CONFIGURATION_FLAG_DRAG = 1,
    INTERACTION_CONFIGURATION_FLAG_MAX = 4294967295,
} INTERACTION_CONFIGURATION_FLAGS;

typedef enum {
    INERTIA_PARAMETER_TRANSLATION_DECELERATION = 1,
    INERTIA_PARAMETER_TRANSLATION_DISPLACEMENT = 2,
    INERTIA_PARAMETER_ROTATION_DECELERATION = 3,
    INERTIA_PARAMETER_ROTATION_ANGLE = 4,
    INERTIA_PARAMETER_EXPANSION_DECELERATION = 5,
    INERTIA_PARAMETER_EXPANSION_EXPANSION = 6,
    INERTIA_PARAMETER_MAX = -1,
} INERTIA_PARAMETER;

typedef enum {
    INTERACTION_STATE_IDLE = 0,
    INTERACTION_STATE_IN_INTERACTION = 1,
    INTERACTION_STATE_POSSIBLE_DOUBLE_TAP = 2,
    INTERACTION_STATE_MAX = -1,
} INTERACTION_STATE;

typedef enum {
    INTERACTION_CONTEXT_PROPERTY_MEASUREMENT_UNITS = 1,
    INTERACTION_CONTEXT_PROPERTY_INTERACTION_UI_FEEDBACK = 2,
    INTERACTION_CONTEXT_PROPERTY_FILTER_POINTERS = 3,
    INTERACTION_CONTEXT_PROPERTY_MAX = -1,
} INTERACTION_CONTEXT_PROPERTY;

typedef enum {
    CROSS_SLIDE_THRESHOLD_SELECT_START = 0,
    CROSS_SLIDE_THRESHOLD_SPEED_BUMP_START = 1,
    CROSS_SLIDE_THRESHOLD_SPEED_BUMP_END = 2,
    CROSS_SLIDE_THRESHOLD_REARRANGE_START = 3,
    CROSS_SLIDE_THRESHOLD_COUNT = 4,
    CROSS_SLIDE_THRESHOLD_MAX = -1,
} CROSS_SLIDE_THRESHOLD;

typedef enum {
    CROSS_SLIDE_FLAGS_NONE = 0,
    CROSS_SLIDE_FLAGS_SELECT = 1,
    CROSS_SLIDE_FLAGS_SPEED_BUMP = 2,
    CROSS_SLIDE_FLAGS_REARRANGE = 4,
    CROSS_SLIDE_FLAGS_MAX = 4294967295,
} CROSS_SLIDE_FLAGS;

typedef enum {
    MOUSE_WHEEL_PARAMETER_CHAR_TRANSLATION_X = 1,
    MOUSE_WHEEL_PARAMETER_CHAR_TRANSLATION_Y = 2,
    MOUSE_WHEEL_PARAMETER_DELTA_SCALE = 3,
    MOUSE_WHEEL_PARAMETER_DELTA_ROTATION = 4,
    MOUSE_WHEEL_PARAMETER_PAGE_TRANSLATION_X = 5,
    MOUSE_WHEEL_PARAMETER_PAGE_TRANSLATION_Y = 6,
    MOUSE_WHEEL_PARAMETER_MAX = -1,
} MOUSE_WHEEL_PARAMETER;

typedef enum {
    TAP_PARAMETER_MIN_CONTACT_COUNT = 0,
    TAP_PARAMETER_MAX_CONTACT_COUNT = 1,
    TAP_PARAMETER_MAX = -1,
} TAP_PARAMETER;

typedef enum {
    HOLD_PARAMETER_MIN_CONTACT_COUNT = 0,
    HOLD_PARAMETER_MAX_CONTACT_COUNT = 1,
    HOLD_PARAMETER_THRESHOLD_RADIUS = 2,
    HOLD_PARAMETER_THRESHOLD_START_DELAY = 3,
    HOLD_PARAMETER_MAX = -1,
} HOLD_PARAMETER;

typedef enum {
    TRANSLATION_PARAMETER_MIN_CONTACT_COUNT = 0,
    TRANSLATION_PARAMETER_MAX_CONTACT_COUNT = 1,
    TRANSLATION_PARAMETER_MAX = -1,
} TRANSLATION_PARAMETER;

typedef enum {
    MANIPULATION_RAILS_STATE_UNDECIDED = 0,
    MANIPULATION_RAILS_STATE_FREE = 1,
    MANIPULATION_RAILS_STATE_RAILED = 2,
    MANIPULATION_RAILS_STATE_MAX = -1,
} MANIPULATION_RAILS_STATE;

typedef int MANIPULATION_TRANSFORM;

typedef int MANIPULATION_VELOCITY;

typedef int INTERACTION_ARGUMENTS_MANIPULATION;

typedef int INTERACTION_ARGUMENTS_TAP;

typedef int INTERACTION_ARGUMENTS_CROSS_SLIDE;

typedef int INTERACTION_CONTEXT_OUTPUT;

typedef int INTERACTION_CONTEXT_OUTPUT2;

typedef int INTERACTION_CONTEXT_CONFIGURATION;

typedef int CROSS_SLIDE_PARAMETER;

typedef int INTERACTION_CONTEXT_OUTPUT_CALLBACK;

typedef int INTERACTION_CONTEXT_OUTPUT_CALLBACK2;


//--------------------------------------------------------------------------------
// Section: Functions (30)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void CreateInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void DestroyInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void RegisterOutputCallbackInteractionContext();

/*HRESULT*/void RegisterOutputCallbackInteractionContext2();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SetInteractionConfigurationInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void GetInteractionConfigurationInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SetPropertyInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void GetPropertyInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SetInertiaParameterInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void GetInertiaParameterInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SetCrossSlideParametersInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void GetCrossSlideParameterInteractionContext();

/*HRESULT*/void SetTapParameterInteractionContext();

/*HRESULT*/void GetTapParameterInteractionContext();

/*HRESULT*/void SetHoldParameterInteractionContext();

/*HRESULT*/void GetHoldParameterInteractionContext();

/*HRESULT*/void SetTranslationParameterInteractionContext();

/*HRESULT*/void GetTranslationParameterInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SetMouseWheelParameterInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void GetMouseWheelParameterInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void ResetInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void GetStateInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void AddPointerInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void RemovePointerInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void ProcessPointerFramesInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void BufferPointerPacketsInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void ProcessBufferedPacketsInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void ProcessInertiaInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void StopInteractionContext();

// TODO: this type is limited to platform 'windows8.0'
/*HRESULT*/void SetPivotInteractionContext();

