// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (5)
//--------------------------------------------------------------------------------
#define MS_SHOWMAGNIFIEDCURSOR (INT)1
#define MS_CLIPAROUNDCURSOR (INT)2
#define MS_INVERTCOLORS (INT)4
#define MW_FILTERMODE_EXCLUDE (UINT)0
#define MW_FILTERMODE_INCLUDE (UINT)1

//--------------------------------------------------------------------------------
// Section: Types (4)
//--------------------------------------------------------------------------------
typedef int MAGTRANSFORM;

typedef int MAGIMAGEHEADER;

typedef int MAGCOLOREFFECT;

typedef int MagImageScalingCallback;


//--------------------------------------------------------------------------------
// Section: Functions (19)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagInitialize();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagUninitialize();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagSetWindowSource();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagGetWindowSource();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagSetWindowTransform();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagGetWindowTransform();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagSetWindowFilterList();

// TODO: this type is limited to platform 'windows6.0.6000'
/*i32*/void MagGetWindowFilterList();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagSetImageScalingCallback();

// TODO: this type is limited to platform 'windows6.0.6000'
/*MagImageScalingCallback*/void MagGetImageScalingCallback();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagSetColorEffect();

// TODO: this type is limited to platform 'windows6.0.6000'
/*BOOL*/void MagGetColorEffect();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagSetFullscreenTransform();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagGetFullscreenTransform();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagSetFullscreenColorEffect();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagGetFullscreenColorEffect();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagSetInputTransform();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagGetInputTransform();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void MagShowSystemCursor();

