// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (0)
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Section: Types (6)
//--------------------------------------------------------------------------------
typedef enum {
    POINTER_FLAG_NONE = 0,
    POINTER_FLAG_NEW = 1,
    POINTER_FLAG_INRANGE = 2,
    POINTER_FLAG_INCONTACT = 4,
    POINTER_FLAG_FIRSTBUTTON = 16,
    POINTER_FLAG_SECONDBUTTON = 32,
    POINTER_FLAG_THIRDBUTTON = 64,
    POINTER_FLAG_FOURTHBUTTON = 128,
    POINTER_FLAG_FIFTHBUTTON = 256,
    POINTER_FLAG_PRIMARY = 8192,
    POINTER_FLAG_CONFIDENCE = 16384,
    POINTER_FLAG_CANCELED = 32768,
    POINTER_FLAG_DOWN = 65536,
    POINTER_FLAG_UPDATE = 131072,
    POINTER_FLAG_UP = 262144,
    POINTER_FLAG_WHEEL = 524288,
    POINTER_FLAG_HWHEEL = 1048576,
    POINTER_FLAG_CAPTURECHANGED = 2097152,
    POINTER_FLAG_HASTRANSFORM = 4194304,
} POINTER_FLAGS;

typedef enum {
    POINTER_CHANGE_NONE = 0,
    POINTER_CHANGE_FIRSTBUTTON_DOWN = 1,
    POINTER_CHANGE_FIRSTBUTTON_UP = 2,
    POINTER_CHANGE_SECONDBUTTON_DOWN = 3,
    POINTER_CHANGE_SECONDBUTTON_UP = 4,
    POINTER_CHANGE_THIRDBUTTON_DOWN = 5,
    POINTER_CHANGE_THIRDBUTTON_UP = 6,
    POINTER_CHANGE_FOURTHBUTTON_DOWN = 7,
    POINTER_CHANGE_FOURTHBUTTON_UP = 8,
    POINTER_CHANGE_FIFTHBUTTON_DOWN = 9,
    POINTER_CHANGE_FIFTHBUTTON_UP = 10,
} POINTER_BUTTON_CHANGE_TYPE;

typedef int POINTER_INFO;

typedef int POINTER_TOUCH_INFO;

typedef int POINTER_PEN_INFO;

typedef int INPUT_TRANSFORM;


//--------------------------------------------------------------------------------
// Section: Functions (19)
//--------------------------------------------------------------------------------
// TODO: this type is limited to platform 'windows8.0'
/*u32*/void GetUnpredictedMessagePos();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerType();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerCursorId();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerInfo();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerInfoHistory();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerFrameInfo();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerFrameInfoHistory();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerTouchInfo();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerTouchInfoHistory();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerFrameTouchInfo();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerFrameTouchInfoHistory();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerPenInfo();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerPenInfoHistory();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerFramePenInfo();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void GetPointerFramePenInfoHistory();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void SkipPointerFrameMessages();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void EnableMouseInPointer();

// TODO: this type is limited to platform 'windows8.0'
/*BOOL*/void IsMouseInPointerEnabled();

// TODO: this type is limited to platform 'windows8.1'
/*BOOL*/void GetPointerInputTransform();

