// NOTE: this file is autogenerated, DO NOT MODIFY
#include "../bootstrap.h"
//--------------------------------------------------------------------------------
// Section: Constants (7)
//--------------------------------------------------------------------------------
#define MILBITMAPEFFECT_SDK_VERSION (UINT)16777216
#define CLSID_MILBitmapEffectGroup GUID { "ac9c1a9a-7e18-4f64-ac7e-47cf7f051e95" }
#define CLSID_MILBitmapEffectBlur GUID { "a924df87-225d-4373-8f5b-b90ec85ae3de" }
#define CLSID_MILBitmapEffectDropShadow GUID { "459a3fbe-d8ac-4692-874b-7a265715aa16" }
#define CLSID_MILBitmapEffectOuterGlow GUID { "e2161bdd-7eb6-4725-9c0b-8a2a1b4f0667" }
#define CLSID_MILBitmapEffectBevel GUID { "fd361dbe-6c9b-4de0-8290-f6400c2737ed" }
#define CLSID_MILBitmapEffectEmboss GUID { "cd299846-824f-47ec-a007-12aa767f2816" }

//--------------------------------------------------------------------------------
// Section: Types (23)
//--------------------------------------------------------------------------------
typedef int MilRectD;

typedef int MilPoint2D;

typedef int MILMatrixF;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectConnectorInfo;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectConnectionsInfo;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectConnections;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffect;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectImpl;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectGroup;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectGroupImpl;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectRenderContext;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectRenderContextImpl;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectFactory;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectPrimitive;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectPrimitiveImpl;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffects;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectConnector;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectInputConnector;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectOutputConnector;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectOutputConnectorImpl;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectInteriorInputConnector;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectInteriorOutputConnector;

// TODO: this type is limited to platform 'windows5.1.2600'
typedef int IMILBitmapEffectEvents;


//--------------------------------------------------------------------------------
// Section: Functions (0)
//--------------------------------------------------------------------------------
